import React from "react";
import axios from "axios";
// Recharts
import { LineChart, Line, CartesianGrid, XAxis, YAxis, Tooltip, Legend, ResponsiveContainer, ComposedChart, Area } from "recharts";
import { Radar, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis } from 'recharts';
//Datos de rescuetime
const Key = "B632wU543wwlr1Aw96D0Jie8Xa806KxiKruYi9_4";
const rescuetimeURL = "https://www.rescuetime.com/anapi/";
const dailyURL = rescuetimeURL + "daily_summary_feed?key=" + Key + "&format=json&restrict_source_type=computers";
// get https://www.rescuetime.com/anapi/data?key={{rescuetime_api}}&resolution_time=day&perspective=rank&restrict_kind=overview&restrict_source_type=computers&interval=week&format=json
const categoryURL = rescuetimeURL + "data?key=" + Key + "&resolution_time=day&perspective=rank&restrict_kind=overview&restrict_source_type=computers&interval=week&format=json";

const diario = [
    {
        "id": 1648018800,
        "date": "2022-03-23",
        "productivity_pulse": 84,
        "very_productive_percentage": 43.9,
        "productive_percentage": 50.6,
        "neutral_percentage": 5.1,
        "distracting_percentage": 0,
        "very_distracting_percentage": 0.3,
        "all_productive_percentage": 94.5,
        "all_distracting_percentage": 0.4,
        "uncategorized_percentage": 0.5,
        "business_percentage": 7.6,
        "communication_and_scheduling_percentage": 2.3,
        "social_networking_percentage": 5.6,
        "design_and_composition_percentage": 3.7,
        "entertainment_percentage": 1.5,
        "news_percentage": 0,
        "software_development_percentage": 32.5,
        "reference_and_learning_percentage": 5.7,
        "shopping_percentage": 0,
        "utilities_percentage": 40.5,
        "total_hours": 9.05,
        "very_productive_hours": 3.97,
        "productive_hours": 4.58,
        "neutral_hours": 0.47,
        "distracting_hours": 0,
        "very_distracting_hours": 0.03,
        "all_productive_hours": 8.55,
        "all_distracting_hours": 0.03,
        "uncategorized_hours": 0.04,
        "business_hours": 0.69,
        "communication_and_scheduling_hours": 0.21,
        "social_networking_hours": 0.51,
        "design_and_composition_hours": 0.33,
        "entertainment_hours": 0.14,
        "news_hours": 0,
        "software_development_hours": 2.94,
        "reference_and_learning_hours": 0.51,
        "shopping_hours": 0,
        "utilities_hours": 3.67,
        "total_duration_formatted": "9h 2m",
        "very_productive_duration_formatted": "3h 58m",
        "productive_duration_formatted": "4h 34m",
        "neutral_duration_formatted": "27m 57s",
        "distracting_duration_formatted": "5s",
        "very_distracting_duration_formatted": "1m 50s",
        "all_productive_duration_formatted": "8h 32m",
        "all_distracting_duration_formatted": "1m 55s",
        "uncategorized_duration_formatted": "2m 27s",
        "business_duration_formatted": "41m 31s",
        "communication_and_scheduling_duration_formatted": "12m 44s",
        "social_networking_duration_formatted": "30m 35s",
        "design_and_composition_duration_formatted": "19m 49s",
        "entertainment_duration_formatted": "8m 21s",
        "news_duration_formatted": "5s",
        "software_development_duration_formatted": "2h 56m",
        "reference_and_learning_duration_formatted": "30m 52s",
        "shopping_duration_formatted": "no time",
        "utilities_duration_formatted": "3h 39m"
    },
    {
        "id": 1647932400,
        "date": "2022-03-22",
        "productivity_pulse": 81,
        "very_productive_percentage": 39.7,
        "productive_percentage": 52.8,
        "neutral_percentage": 4.8,
        "distracting_percentage": 0,
        "very_distracting_percentage": 2.6,
        "all_productive_percentage": 92.6,
        "all_distracting_percentage": 2.6,
        "uncategorized_percentage": 2.6,
        "business_percentage": 8,
        "communication_and_scheduling_percentage": 2.1,
        "social_networking_percentage": 2.9,
        "design_and_composition_percentage": 0.4,
        "entertainment_percentage": 0.4,
        "news_percentage": 2.1,
        "software_development_percentage": 30.2,
        "reference_and_learning_percentage": 11.1,
        "shopping_percentage": 0,
        "utilities_percentage": 40.2,
        "total_hours": 17.66,
        "very_productive_hours": 7.01,
        "productive_hours": 9.33,
        "neutral_hours": 0.85,
        "distracting_hours": 0,
        "very_distracting_hours": 0.47,
        "all_productive_hours": 16.34,
        "all_distracting_hours": 0.47,
        "uncategorized_hours": 0.46,
        "business_hours": 1.41,
        "communication_and_scheduling_hours": 0.38,
        "social_networking_hours": 0.51,
        "design_and_composition_hours": 0.08,
        "entertainment_hours": 0.07,
        "news_hours": 0.38,
        "software_development_hours": 5.33,
        "reference_and_learning_hours": 1.96,
        "shopping_hours": 0,
        "utilities_hours": 7.09,
        "total_duration_formatted": "17h 39m",
        "very_productive_duration_formatted": "7h",
        "productive_duration_formatted": "9h 19m",
        "neutral_duration_formatted": "50m 50s",
        "distracting_duration_formatted": "no time",
        "very_distracting_duration_formatted": "28m 3s",
        "all_productive_duration_formatted": "16h 20m",
        "all_distracting_duration_formatted": "28m 3s",
        "uncategorized_duration_formatted": "27m 20s",
        "business_duration_formatted": "1h 24m",
        "communication_and_scheduling_duration_formatted": "22m 30s",
        "social_networking_duration_formatted": "30m 40s",
        "design_and_composition_duration_formatted": "4m 39s",
        "entertainment_duration_formatted": "4m 22s",
        "news_duration_formatted": "22m 35s",
        "software_development_duration_formatted": "5h 19m",
        "reference_and_learning_duration_formatted": "1h 57m",
        "shopping_duration_formatted": "13s",
        "utilities_duration_formatted": "7h 5m"
    },
    {
        "id": 1647846000,
        "date": "2022-03-21",
        "productivity_pulse": 86,
        "very_productive_percentage": 57.4,
        "productive_percentage": 34.1,
        "neutral_percentage": 6.5,
        "distracting_percentage": 1,
        "very_distracting_percentage": 1,
        "all_productive_percentage": 91.5,
        "all_distracting_percentage": 2,
        "uncategorized_percentage": 5.8,
        "business_percentage": 9.2,
        "communication_and_scheduling_percentage": 2.1,
        "social_networking_percentage": 0.5,
        "design_and_composition_percentage": 7.7,
        "entertainment_percentage": 0.3,
        "news_percentage": 0.4,
        "software_development_percentage": 40.5,
        "reference_and_learning_percentage": 9.3,
        "shopping_percentage": 0,
        "utilities_percentage": 24.2,
        "total_hours": 11.13,
        "very_productive_hours": 6.39,
        "productive_hours": 3.79,
        "neutral_hours": 0.73,
        "distracting_hours": 0.11,
        "very_distracting_hours": 0.11,
        "all_productive_hours": 10.18,
        "all_distracting_hours": 0.22,
        "uncategorized_hours": 0.64,
        "business_hours": 1.02,
        "communication_and_scheduling_hours": 0.23,
        "social_networking_hours": 0.06,
        "design_and_composition_hours": 0.86,
        "entertainment_hours": 0.04,
        "news_hours": 0.05,
        "software_development_hours": 4.5,
        "reference_and_learning_hours": 1.03,
        "shopping_hours": 0,
        "utilities_hours": 2.69,
        "total_duration_formatted": "11h 7m",
        "very_productive_duration_formatted": "6h 23m",
        "productive_duration_formatted": "3h 47m",
        "neutral_duration_formatted": "43m 42s",
        "distracting_duration_formatted": "6m 32s",
        "very_distracting_duration_formatted": "6m 47s",
        "all_productive_duration_formatted": "10h 10m",
        "all_distracting_duration_formatted": "13m 19s",
        "uncategorized_duration_formatted": "38m 34s",
        "business_duration_formatted": "1h 1m",
        "communication_and_scheduling_duration_formatted": "14m 3s",
        "social_networking_duration_formatted": "3m 28s",
        "design_and_composition_duration_formatted": "51m 38s",
        "entertainment_duration_formatted": "2m 16s",
        "news_duration_formatted": "2m 45s",
        "software_development_duration_formatted": "4h 30m",
        "reference_and_learning_duration_formatted": "1h 2m",
        "shopping_duration_formatted": "no time",
        "utilities_duration_formatted": "2h 41m"
    },
    {
        "id": 1647759600,
        "date": "2022-03-20",
        "productivity_pulse": 81,
        "very_productive_percentage": 56.3,
        "productive_percentage": 18.2,
        "neutral_percentage": 23.2,
        "distracting_percentage": 0,
        "very_distracting_percentage": 2.3,
        "all_productive_percentage": 74.5,
        "all_distracting_percentage": 2.3,
        "uncategorized_percentage": 23.2,
        "business_percentage": 1.2,
        "communication_and_scheduling_percentage": 0,
        "social_networking_percentage": 0,
        "design_and_composition_percentage": 41.1,
        "entertainment_percentage": 2.3,
        "news_percentage": 0,
        "software_development_percentage": 9.9,
        "reference_and_learning_percentage": 22.3,
        "shopping_percentage": 0,
        "utilities_percentage": 0.1,
        "total_hours": 0.3,
        "very_productive_hours": 0.17,
        "productive_hours": 0.06,
        "neutral_hours": 0.07,
        "distracting_hours": 0,
        "very_distracting_hours": 0.01,
        "all_productive_hours": 0.23,
        "all_distracting_hours": 0.01,
        "uncategorized_hours": 0.07,
        "business_hours": 0,
        "communication_and_scheduling_hours": 0,
        "social_networking_hours": 0,
        "design_and_composition_hours": 0.13,
        "entertainment_hours": 0.01,
        "news_hours": 0,
        "software_development_hours": 0.03,
        "reference_and_learning_hours": 0.07,
        "shopping_hours": 0,
        "utilities_hours": 0,
        "total_duration_formatted": "18m 16s",
        "very_productive_duration_formatted": "10m 17s",
        "productive_duration_formatted": "3m 20s",
        "neutral_duration_formatted": "4m 14s",
        "distracting_duration_formatted": "no time",
        "very_distracting_duration_formatted": "25s",
        "all_productive_duration_formatted": "13m 37s",
        "all_distracting_duration_formatted": "25s",
        "uncategorized_duration_formatted": "4m 14s",
        "business_duration_formatted": "13s",
        "communication_and_scheduling_duration_formatted": "no time",
        "social_networking_duration_formatted": "no time",
        "design_and_composition_duration_formatted": "7m 31s",
        "entertainment_duration_formatted": "25s",
        "news_duration_formatted": "no time",
        "software_development_duration_formatted": "1m 48s",
        "reference_and_learning_duration_formatted": "4m 4s",
        "shopping_duration_formatted": "no time",
        "utilities_duration_formatted": "1s"
    },
    {
        "id": 1647673200,
        "date": "2022-03-19",
        "productivity_pulse": 79,
        "very_productive_percentage": 52,
        "productive_percentage": 29.8,
        "neutral_percentage": 9.6,
        "distracting_percentage": 0,
        "very_distracting_percentage": 8.5,
        "all_productive_percentage": 81.8,
        "all_distracting_percentage": 8.5,
        "uncategorized_percentage": 9.6,
        "business_percentage": 8,
        "communication_and_scheduling_percentage": 0,
        "social_networking_percentage": 6.7,
        "design_and_composition_percentage": 36.9,
        "entertainment_percentage": 1.8,
        "news_percentage": 0,
        "software_development_percentage": 7,
        "reference_and_learning_percentage": 4.6,
        "shopping_percentage": 0,
        "utilities_percentage": 25.3,
        "total_hours": 0.79,
        "very_productive_hours": 0.41,
        "productive_hours": 0.24,
        "neutral_hours": 0.08,
        "distracting_hours": 0,
        "very_distracting_hours": 0.07,
        "all_productive_hours": 0.65,
        "all_distracting_hours": 0.07,
        "uncategorized_hours": 0.08,
        "business_hours": 0.06,
        "communication_and_scheduling_hours": 0,
        "social_networking_hours": 0.05,
        "design_and_composition_hours": 0.29,
        "entertainment_hours": 0.01,
        "news_hours": 0,
        "software_development_hours": 0.06,
        "reference_and_learning_hours": 0.04,
        "shopping_hours": 0,
        "utilities_hours": 0.2,
        "total_duration_formatted": "47m 25s",
        "very_productive_duration_formatted": "24m 39s",
        "productive_duration_formatted": "14m 9s",
        "neutral_duration_formatted": "4m 34s",
        "distracting_duration_formatted": "no time",
        "very_distracting_duration_formatted": "4m 3s",
        "all_productive_duration_formatted": "38m 48s",
        "all_distracting_duration_formatted": "4m 3s",
        "uncategorized_duration_formatted": "4m 34s",
        "business_duration_formatted": "3m 48s",
        "communication_and_scheduling_duration_formatted": "no time",
        "social_networking_duration_formatted": "3m 12s",
        "design_and_composition_duration_formatted": "17m 30s",
        "entertainment_duration_formatted": "51s",
        "news_duration_formatted": "no time",
        "software_development_duration_formatted": "3m 20s",
        "reference_and_learning_duration_formatted": "2m 10s",
        "shopping_duration_formatted": "no time",
        "utilities_duration_formatted": "12m"
    },
    {
        "id": 1647586800,
        "date": "2022-03-18",
        "productivity_pulse": 89,
        "very_productive_percentage": 60.9,
        "productive_percentage": 36.6,
        "neutral_percentage": 2.4,
        "distracting_percentage": 0,
        "very_distracting_percentage": 0.1,
        "all_productive_percentage": 97.5,
        "all_distracting_percentage": 0.1,
        "uncategorized_percentage": 2.1,
        "business_percentage": 32,
        "communication_and_scheduling_percentage": 1.7,
        "social_networking_percentage": 0.8,
        "design_and_composition_percentage": 0.1,
        "entertainment_percentage": 0,
        "news_percentage": 0.1,
        "software_development_percentage": 27.5,
        "reference_and_learning_percentage": 2.4,
        "shopping_percentage": 0,
        "utilities_percentage": 33.3,
        "total_hours": 7.08,
        "very_productive_hours": 4.31,
        "productive_hours": 2.59,
        "neutral_hours": 0.17,
        "distracting_hours": 0,
        "very_distracting_hours": 0.01,
        "all_productive_hours": 6.9,
        "all_distracting_hours": 0.01,
        "uncategorized_hours": 0.15,
        "business_hours": 2.27,
        "communication_and_scheduling_hours": 0.12,
        "social_networking_hours": 0.05,
        "design_and_composition_hours": 0.01,
        "entertainment_hours": 0,
        "news_hours": 0.01,
        "software_development_hours": 1.95,
        "reference_and_learning_hours": 0.17,
        "shopping_hours": 0,
        "utilities_hours": 2.36,
        "total_duration_formatted": "7h 4m",
        "very_productive_duration_formatted": "4h 18m",
        "productive_duration_formatted": "2h 35m",
        "neutral_duration_formatted": "10m 17s",
        "distracting_duration_formatted": "no time",
        "very_distracting_duration_formatted": "28s",
        "all_productive_duration_formatted": "6h 54m",
        "all_distracting_duration_formatted": "28s",
        "uncategorized_duration_formatted": "8m 55s",
        "business_duration_formatted": "2h 15m",
        "communication_and_scheduling_duration_formatted": "7m 9s",
        "social_networking_duration_formatted": "3m 17s",
        "design_and_composition_duration_formatted": "28s",
        "entertainment_duration_formatted": "no time",
        "news_duration_formatted": "24s",
        "software_development_duration_formatted": "1h 57m",
        "reference_and_learning_duration_formatted": "10m 1s",
        "shopping_duration_formatted": "4s",
        "utilities_duration_formatted": "2h 21m"
    },
    {
        "id": 1647500400,
        "date": "2022-03-17",
        "productivity_pulse": 89,
        "very_productive_percentage": 64.7,
        "productive_percentage": 29.4,
        "neutral_percentage": 5.9,
        "distracting_percentage": 0,
        "very_distracting_percentage": 0,
        "all_productive_percentage": 94.1,
        "all_distracting_percentage": 0,
        "uncategorized_percentage": 5.8,
        "business_percentage": 6.6,
        "communication_and_scheduling_percentage": 0,
        "social_networking_percentage": 0,
        "design_and_composition_percentage": 0,
        "entertainment_percentage": 0.1,
        "news_percentage": 0,
        "software_development_percentage": 58.1,
        "reference_and_learning_percentage": 1,
        "shopping_percentage": 0,
        "utilities_percentage": 28.3,
        "total_hours": 3.61,
        "very_productive_hours": 2.34,
        "productive_hours": 1.06,
        "neutral_hours": 0.21,
        "distracting_hours": 0,
        "very_distracting_hours": 0,
        "all_productive_hours": 3.4,
        "all_distracting_hours": 0,
        "uncategorized_hours": 0.21,
        "business_hours": 0.24,
        "communication_and_scheduling_hours": 0,
        "social_networking_hours": 0,
        "design_and_composition_hours": 0,
        "entertainment_hours": 0,
        "news_hours": 0,
        "software_development_hours": 2.1,
        "reference_and_learning_hours": 0.04,
        "shopping_hours": 0,
        "utilities_hours": 1.02,
        "total_duration_formatted": "3h 36m",
        "very_productive_duration_formatted": "2h 20m",
        "productive_duration_formatted": "1h 3m",
        "neutral_duration_formatted": "12m 45s",
        "distracting_duration_formatted": "no time",
        "very_distracting_duration_formatted": "no time",
        "all_productive_duration_formatted": "3h 24m",
        "all_distracting_duration_formatted": "no time",
        "uncategorized_duration_formatted": "12m 35s",
        "business_duration_formatted": "14m 25s",
        "communication_and_scheduling_duration_formatted": "no time",
        "social_networking_duration_formatted": "no time",
        "design_and_composition_duration_formatted": "no time",
        "entertainment_duration_formatted": "10s",
        "news_duration_formatted": "no time",
        "software_development_duration_formatted": "2h 5m",
        "reference_and_learning_duration_formatted": "2m 16s",
        "shopping_duration_formatted": "no time",
        "utilities_duration_formatted": "1h 1m"
    },
    {
        "id": 1647414000,
        "date": "2022-03-16",
        "productivity_pulse": 72,
        "very_productive_percentage": 21.7,
        "productive_percentage": 60.5,
        "neutral_percentage": 11.7,
        "distracting_percentage": 0.1,
        "very_distracting_percentage": 6,
        "all_productive_percentage": 82.1,
        "all_distracting_percentage": 6.1,
        "uncategorized_percentage": 9.9,
        "business_percentage": 4.3,
        "communication_and_scheduling_percentage": 0.1,
        "social_networking_percentage": 7.5,
        "design_and_composition_percentage": 2.8,
        "entertainment_percentage": 2.9,
        "news_percentage": 0.1,
        "software_development_percentage": 5.1,
        "reference_and_learning_percentage": 15.6,
        "shopping_percentage": 0.4,
        "utilities_percentage": 51.4,
        "total_hours": 8.44,
        "very_productive_hours": 1.83,
        "productive_hours": 5.1,
        "neutral_hours": 0.99,
        "distracting_hours": 0.01,
        "very_distracting_hours": 0.51,
        "all_productive_hours": 6.93,
        "all_distracting_hours": 0.52,
        "uncategorized_hours": 0.84,
        "business_hours": 0.36,
        "communication_and_scheduling_hours": 0.01,
        "social_networking_hours": 0.64,
        "design_and_composition_hours": 0.24,
        "entertainment_hours": 0.24,
        "news_hours": 0.01,
        "software_development_hours": 0.43,
        "reference_and_learning_hours": 1.31,
        "shopping_hours": 0.03,
        "utilities_hours": 4.34,
        "total_duration_formatted": "8h 26m",
        "very_productive_duration_formatted": "1h 49m",
        "productive_duration_formatted": "5h 6m",
        "neutral_duration_formatted": "59m 30s",
        "distracting_duration_formatted": "22s",
        "very_distracting_duration_formatted": "30m 36s",
        "all_productive_duration_formatted": "6h 56m",
        "all_distracting_duration_formatted": "30m 58s",
        "uncategorized_duration_formatted": "50m 17s",
        "business_duration_formatted": "21m 50s",
        "communication_and_scheduling_duration_formatted": "22s",
        "social_networking_duration_formatted": "38m 9s",
        "design_and_composition_duration_formatted": "14m 7s",
        "entertainment_duration_formatted": "14m 31s",
        "news_duration_formatted": "22s",
        "software_development_duration_formatted": "25m 56s",
        "reference_and_learning_duration_formatted": "1h 18m",
        "shopping_duration_formatted": "2m 1s",
        "utilities_duration_formatted": "4h 20m"
    },
    {
        "id": 1647327600,
        "date": "2022-03-15",
        "productivity_pulse": 82,
        "very_productive_percentage": 47.4,
        "productive_percentage": 39.7,
        "neutral_percentage": 11.1,
        "distracting_percentage": 0.7,
        "very_distracting_percentage": 1.2,
        "all_productive_percentage": 87.1,
        "all_distracting_percentage": 1.9,
        "uncategorized_percentage": 4.4,
        "business_percentage": 21.3,
        "communication_and_scheduling_percentage": 4.8,
        "social_networking_percentage": 1.2,
        "design_and_composition_percentage": 14.8,
        "entertainment_percentage": 0,
        "news_percentage": 0,
        "software_development_percentage": 11.3,
        "reference_and_learning_percentage": 13.7,
        "shopping_percentage": 0,
        "utilities_percentage": 28.6,
        "total_hours": 4.83,
        "very_productive_hours": 2.29,
        "productive_hours": 1.92,
        "neutral_hours": 0.53,
        "distracting_hours": 0.03,
        "very_distracting_hours": 0.06,
        "all_productive_hours": 4.2,
        "all_distracting_hours": 0.09,
        "uncategorized_hours": 0.21,
        "business_hours": 1.03,
        "communication_and_scheduling_hours": 0.23,
        "social_networking_hours": 0.06,
        "design_and_composition_hours": 0.71,
        "entertainment_hours": 0,
        "news_hours": 0,
        "software_development_hours": 0.54,
        "reference_and_learning_hours": 0.66,
        "shopping_hours": 0,
        "utilities_hours": 1.38,
        "total_duration_formatted": "4h 49m",
        "very_productive_duration_formatted": "2h 17m",
        "productive_duration_formatted": "1h 54m",
        "neutral_duration_formatted": "32m 4s",
        "distracting_duration_formatted": "1m 55s",
        "very_distracting_duration_formatted": "3m 27s",
        "all_productive_duration_formatted": "4h 12m",
        "all_distracting_duration_formatted": "5m 22s",
        "uncategorized_duration_formatted": "12m 40s",
        "business_duration_formatted": "1h 1m",
        "communication_and_scheduling_duration_formatted": "13m 46s",
        "social_networking_duration_formatted": "3m 27s",
        "design_and_composition_duration_formatted": "42m 46s",
        "entertainment_duration_formatted": "no time",
        "news_duration_formatted": "no time",
        "software_development_duration_formatted": "32m 36s",
        "reference_and_learning_duration_formatted": "39m 43s",
        "shopping_duration_formatted": "no time",
        "utilities_duration_formatted": "1h 22m"
    },
    {
        "id": 1647241200,
        "date": "2022-03-14",
        "productivity_pulse": 64,
        "very_productive_percentage": 27.5,
        "productive_percentage": 35.2,
        "neutral_percentage": 9.9,
        "distracting_percentage": 21.2,
        "very_distracting_percentage": 6.2,
        "all_productive_percentage": 62.7,
        "all_distracting_percentage": 27.4,
        "uncategorized_percentage": 5.3,
        "business_percentage": 0.5,
        "communication_and_scheduling_percentage": 22,
        "social_networking_percentage": 6.1,
        "design_and_composition_percentage": 7.4,
        "entertainment_percentage": 4.3,
        "news_percentage": 2.8,
        "software_development_percentage": 16.8,
        "reference_and_learning_percentage": 11.6,
        "shopping_percentage": 0,
        "utilities_percentage": 23.1,
        "total_hours": 12.1,
        "very_productive_hours": 3.33,
        "productive_hours": 4.26,
        "neutral_hours": 1.19,
        "distracting_hours": 2.56,
        "very_distracting_hours": 0.76,
        "all_productive_hours": 7.58,
        "all_distracting_hours": 3.32,
        "uncategorized_hours": 0.65,
        "business_hours": 0.06,
        "communication_and_scheduling_hours": 2.66,
        "social_networking_hours": 0.74,
        "design_and_composition_hours": 0.89,
        "entertainment_hours": 0.52,
        "news_hours": 0.34,
        "software_development_hours": 2.03,
        "reference_and_learning_hours": 1.4,
        "shopping_hours": 0,
        "utilities_hours": 2.8,
        "total_duration_formatted": "12h 5m",
        "very_productive_duration_formatted": "3h 19m",
        "productive_duration_formatted": "4h 15m",
        "neutral_duration_formatted": "1h 11m",
        "distracting_duration_formatted": "2h 33m",
        "very_distracting_duration_formatted": "45m 19s",
        "all_productive_duration_formatted": "7h 35m",
        "all_distracting_duration_formatted": "3h 19m",
        "uncategorized_duration_formatted": "38m 48s",
        "business_duration_formatted": "3m 30s",
        "communication_and_scheduling_duration_formatted": "2h 39m",
        "social_networking_duration_formatted": "44m 34s",
        "design_and_composition_duration_formatted": "53m 33s",
        "entertainment_duration_formatted": "31m 2s",
        "news_duration_formatted": "20m 39s",
        "software_development_duration_formatted": "2h 2m",
        "reference_and_learning_duration_formatted": "1h 24m",
        "shopping_duration_formatted": "9s",
        "utilities_duration_formatted": "2h 47m"
    },
    {
        "id": 1647158400,
        "date": "2022-03-13",
        "productivity_pulse": 38,
        "very_productive_percentage": 12.9,
        "productive_percentage": 20.1,
        "neutral_percentage": 10,
        "distracting_percentage": 20.6,
        "very_distracting_percentage": 36.4,
        "all_productive_percentage": 33,
        "all_distracting_percentage": 57,
        "uncategorized_percentage": 0,
        "business_percentage": 0.2,
        "communication_and_scheduling_percentage": 23.1,
        "social_networking_percentage": 9.2,
        "design_and_composition_percentage": 10.8,
        "entertainment_percentage": 35.5,
        "news_percentage": 2.7,
        "software_development_percentage": 0.1,
        "reference_and_learning_percentage": 15.6,
        "shopping_percentage": 0,
        "utilities_percentage": 2.9,
        "total_hours": 4.54,
        "very_productive_hours": 0.58,
        "productive_hours": 0.91,
        "neutral_hours": 0.45,
        "distracting_hours": 0.93,
        "very_distracting_hours": 1.65,
        "all_productive_hours": 1.5,
        "all_distracting_hours": 2.59,
        "uncategorized_hours": 0,
        "business_hours": 0.01,
        "communication_and_scheduling_hours": 1.05,
        "social_networking_hours": 0.42,
        "design_and_composition_hours": 0.49,
        "entertainment_hours": 1.61,
        "news_hours": 0.12,
        "software_development_hours": 0,
        "reference_and_learning_hours": 0.71,
        "shopping_hours": 0,
        "utilities_hours": 0.13,
        "total_duration_formatted": "4h 32m",
        "very_productive_duration_formatted": "35m",
        "productive_duration_formatted": "54m 49s",
        "neutral_duration_formatted": "27m 11s",
        "distracting_duration_formatted": "56m",
        "very_distracting_duration_formatted": "1h 39m",
        "all_productive_duration_formatted": "1h 29m",
        "all_distracting_duration_formatted": "2h 35m",
        "uncategorized_duration_formatted": "3s",
        "business_duration_formatted": "35s",
        "communication_and_scheduling_duration_formatted": "1h 2m",
        "social_networking_duration_formatted": "25m 6s",
        "design_and_composition_duration_formatted": "29m 28s",
        "entertainment_duration_formatted": "1h 36m",
        "news_duration_formatted": "7m 14s",
        "software_development_duration_formatted": "12s",
        "reference_and_learning_duration_formatted": "42m 23s",
        "shopping_duration_formatted": "no time",
        "utilities_duration_formatted": "7m 52s"
    },
    {
        "id": 1647072000,
        "date": "2022-03-12",
        "productivity_pulse": 55,
        "very_productive_percentage": 15.5,
        "productive_percentage": 40.6,
        "neutral_percentage": 2.3,
        "distracting_percentage": 35,
        "very_distracting_percentage": 6.6,
        "all_productive_percentage": 56.1,
        "all_distracting_percentage": 41.6,
        "uncategorized_percentage": 0.1,
        "business_percentage": 0.7,
        "communication_and_scheduling_percentage": 37.6,
        "social_networking_percentage": 9.6,
        "design_and_composition_percentage": 14.8,
        "entertainment_percentage": 2.4,
        "news_percentage": 5.2,
        "software_development_percentage": 0,
        "reference_and_learning_percentage": 16.3,
        "shopping_percentage": 0.9,
        "utilities_percentage": 12.3,
        "total_hours": 3.47,
        "very_productive_hours": 0.54,
        "productive_hours": 1.41,
        "neutral_hours": 0.08,
        "distracting_hours": 1.21,
        "very_distracting_hours": 0.23,
        "all_productive_hours": 1.94,
        "all_distracting_hours": 1.44,
        "uncategorized_hours": 0,
        "business_hours": 0.02,
        "communication_and_scheduling_hours": 1.31,
        "social_networking_hours": 0.33,
        "design_and_composition_hours": 0.51,
        "entertainment_hours": 0.08,
        "news_hours": 0.18,
        "software_development_hours": 0,
        "reference_and_learning_hours": 0.57,
        "shopping_hours": 0.03,
        "utilities_hours": 0.43,
        "total_duration_formatted": "3h 28m",
        "very_productive_duration_formatted": "32m 18s",
        "productive_duration_formatted": "1h 24m",
        "neutral_duration_formatted": "4m 53s",
        "distracting_duration_formatted": "1h 12m",
        "very_distracting_duration_formatted": "13m 40s",
        "all_productive_duration_formatted": "1h 56m",
        "all_distracting_duration_formatted": "1h 26m",
        "uncategorized_duration_formatted": "7s",
        "business_duration_formatted": "1m 25s",
        "communication_and_scheduling_duration_formatted": "1h 18m",
        "social_networking_duration_formatted": "20m 2s",
        "design_and_composition_duration_formatted": "30m 51s",
        "entertainment_duration_formatted": "5m 5s",
        "news_duration_formatted": "10m 55s",
        "software_development_duration_formatted": "2s",
        "reference_and_learning_duration_formatted": "33m 57s",
        "shopping_duration_formatted": "1m 50s",
        "utilities_duration_formatted": "25m 32s"
    },
    {
        "id": 1646985600,
        "date": "2022-03-11",
        "productivity_pulse": 62,
        "very_productive_percentage": 25.3,
        "productive_percentage": 35.7,
        "neutral_percentage": 14.1,
        "distracting_percentage": 14,
        "very_distracting_percentage": 10.9,
        "all_productive_percentage": 61,
        "all_distracting_percentage": 24.9,
        "uncategorized_percentage": 5,
        "business_percentage": 2,
        "communication_and_scheduling_percentage": 16.2,
        "social_networking_percentage": 5.8,
        "design_and_composition_percentage": 9.2,
        "entertainment_percentage": 8.9,
        "news_percentage": 0.8,
        "software_development_percentage": 13.2,
        "reference_and_learning_percentage": 20.5,
        "shopping_percentage": 0,
        "utilities_percentage": 18.3,
        "total_hours": 13.86,
        "very_productive_hours": 3.51,
        "productive_hours": 4.94,
        "neutral_hours": 1.96,
        "distracting_hours": 1.94,
        "very_distracting_hours": 1.51,
        "all_productive_hours": 8.45,
        "all_distracting_hours": 3.45,
        "uncategorized_hours": 0.7,
        "business_hours": 0.28,
        "communication_and_scheduling_hours": 2.25,
        "social_networking_hours": 0.8,
        "design_and_composition_hours": 1.28,
        "entertainment_hours": 1.23,
        "news_hours": 0.12,
        "software_development_hours": 1.83,
        "reference_and_learning_hours": 2.84,
        "shopping_hours": 0,
        "utilities_hours": 2.54,
        "total_duration_formatted": "13h 51m",
        "very_productive_duration_formatted": "3h 30m",
        "productive_duration_formatted": "4h 56m",
        "neutral_duration_formatted": "1h 57m",
        "distracting_duration_formatted": "1h 56m",
        "very_distracting_duration_formatted": "1h 30m",
        "all_productive_duration_formatted": "8h 26m",
        "all_distracting_duration_formatted": "3h 27m",
        "uncategorized_duration_formatted": "41m 54s",
        "business_duration_formatted": "16m 51s",
        "communication_and_scheduling_duration_formatted": "2h 14m",
        "social_networking_duration_formatted": "48m 15s",
        "design_and_composition_duration_formatted": "1h 16m",
        "entertainment_duration_formatted": "1h 13m",
        "news_duration_formatted": "6m 57s",
        "software_development_duration_formatted": "1h 49m",
        "reference_and_learning_duration_formatted": "2h 50m",
        "shopping_duration_formatted": "no time",
        "utilities_duration_formatted": "2h 32m"
    },
    {
        "id": 1646899200,
        "date": "2022-03-10",
        "productivity_pulse": 64,
        "very_productive_percentage": 25.5,
        "productive_percentage": 41.7,
        "neutral_percentage": 6.7,
        "distracting_percentage": 16.1,
        "very_distracting_percentage": 10.1,
        "all_productive_percentage": 67.1,
        "all_distracting_percentage": 26.1,
        "uncategorized_percentage": 4.1,
        "business_percentage": 2.1,
        "communication_and_scheduling_percentage": 9.6,
        "social_networking_percentage": 8.7,
        "design_and_composition_percentage": 5.2,
        "entertainment_percentage": 14.9,
        "news_percentage": 0.4,
        "software_development_percentage": 13.1,
        "reference_and_learning_percentage": 8.4,
        "shopping_percentage": 0.2,
        "utilities_percentage": 33.3,
        "total_hours": 18.1,
        "very_productive_hours": 4.61,
        "productive_hours": 7.55,
        "neutral_hours": 1.22,
        "distracting_hours": 2.91,
        "very_distracting_hours": 1.83,
        "all_productive_hours": 12.15,
        "all_distracting_hours": 4.73,
        "uncategorized_hours": 0.75,
        "business_hours": 0.38,
        "communication_and_scheduling_hours": 1.74,
        "social_networking_hours": 1.58,
        "design_and_composition_hours": 0.94,
        "entertainment_hours": 2.7,
        "news_hours": 0.07,
        "software_development_hours": 2.36,
        "reference_and_learning_hours": 1.52,
        "shopping_hours": 0.04,
        "utilities_hours": 6.03,
        "total_duration_formatted": "18h 6m",
        "very_productive_duration_formatted": "4h 36m",
        "productive_duration_formatted": "7h 32m",
        "neutral_duration_formatted": "1h 12m",
        "distracting_duration_formatted": "2h 54m",
        "very_distracting_duration_formatted": "1h 49m",
        "all_productive_duration_formatted": "12h 9m",
        "all_distracting_duration_formatted": "4h 43m",
        "uncategorized_duration_formatted": "44m 52s",
        "business_duration_formatted": "22m 47s",
        "communication_and_scheduling_duration_formatted": "1h 44m",
        "social_networking_duration_formatted": "1h 34m",
        "design_and_composition_duration_formatted": "56m 7s",
        "entertainment_duration_formatted": "2h 42m",
        "news_duration_formatted": "4m 18s",
        "software_development_duration_formatted": "2h 21m",
        "reference_and_learning_duration_formatted": "1h 31m",
        "shopping_duration_formatted": "2m 8s",
        "utilities_duration_formatted": "6h 1m"
    },
    {
        "id": 1646812800,
        "date": "2022-03-09",
        "productivity_pulse": 59,
        "very_productive_percentage": 25.1,
        "productive_percentage": 35.7,
        "neutral_percentage": 5.5,
        "distracting_percentage": 21.1,
        "very_distracting_percentage": 12.7,
        "all_productive_percentage": 60.7,
        "all_distracting_percentage": 33.8,
        "uncategorized_percentage": 1,
        "business_percentage": 7.1,
        "communication_and_scheduling_percentage": 23,
        "social_networking_percentage": 21.4,
        "design_and_composition_percentage": 8.6,
        "entertainment_percentage": 7.9,
        "news_percentage": 3.5,
        "software_development_percentage": 7.3,
        "reference_and_learning_percentage": 13.7,
        "shopping_percentage": 0.2,
        "utilities_percentage": 6,
        "total_hours": 9.35,
        "very_productive_hours": 2.34,
        "productive_hours": 3.34,
        "neutral_hours": 0.52,
        "distracting_hours": 1.97,
        "very_distracting_hours": 1.19,
        "all_productive_hours": 5.68,
        "all_distracting_hours": 3.16,
        "uncategorized_hours": 0.09,
        "business_hours": 0.66,
        "communication_and_scheduling_hours": 2.15,
        "social_networking_hours": 2,
        "design_and_composition_hours": 0.81,
        "entertainment_hours": 0.73,
        "news_hours": 0.33,
        "software_development_hours": 0.69,
        "reference_and_learning_hours": 1.28,
        "shopping_hours": 0.02,
        "utilities_hours": 0.56,
        "total_duration_formatted": "9h 21m",
        "very_productive_duration_formatted": "2h 20m",
        "productive_duration_formatted": "3h 20m",
        "neutral_duration_formatted": "30m 56s",
        "distracting_duration_formatted": "1h 58m",
        "very_distracting_duration_formatted": "1h 11m",
        "all_productive_duration_formatted": "5h 40m",
        "all_distracting_duration_formatted": "3h 9m",
        "uncategorized_duration_formatted": "5m 27s",
        "business_duration_formatted": "39m 34s",
        "communication_and_scheduling_duration_formatted": "2h 8m",
        "social_networking_duration_formatted": "1h 59m",
        "design_and_composition_duration_formatted": "48m 24s",
        "entertainment_duration_formatted": "44m 3s",
        "news_duration_formatted": "19m 55s",
        "software_development_duration_formatted": "41m 10s",
        "reference_and_learning_duration_formatted": "1h 16m",
        "shopping_duration_formatted": "1m 1s",
        "utilities_duration_formatted": "33m 33s"
    }
]
const categoria = [
    [
        1,
        35132,
        1,
        "Software Development"
    ],
    [
        2,
        22626,
        1,
        "Utilities"
    ],
    [
        3,
        3959,
        1,
        "Reference & Learning"
    ],
    [
        4,
        2046,
        1,
        "Business"
    ],
    [
        5,
        1295,
        1,
        "Uncategorized"
    ],
    [
        6,
        690,
        1,
        "Design & Composition"
    ],
    [
        7,
        625,
        1,
        "Social Networking"
    ],
    [
        8,
        378,
        1,
        "News & Opinion"
    ],
    [
        9,
        138,
        1,
        "Communication & Scheduling"
    ],
    [
        10,
        122,
        1,
        "Entertainment"
    ]
]

const Rescuetime = () => {
    const [daily, setDaily] = React.useState([]);
    const [category, setCategory] = React.useState([]);

     const CORS_SERVER = 'https://cors-anywhere.herokuapp.com/'
    // const CORS_SERVER = 'http://localhost:8080/'

    React.useEffect(() => {
        axios({
            method: 'get',
            url: CORS_SERVER + dailyURL,
        }).then(res => {
            setDaily(res.data);
            console.log(res.data)
        }).catch(err => {
            console.log("error", err)
            console.log("usando datos daily del recuerdo")
            setDaily(diario)
        })
        axios({
            method: 'get',
            url: CORS_SERVER + categoryURL,
        }).then(res => {
            setCategory(res.data.rows);
            console.log(res.data.rows)
        }).catch(err => {
            console.log("error", err);
            console.log("usando datos del recuerdo overview")
            setCategory(categoria)
        })
    }, [])


    function convertirFecha(fechaString) {
        var fechaSp = fechaString.split("-");
        var anio = fechaSp[2];
        var mes = fechaSp[1] - 1;
        var dia = fechaSp[0];
        return new Date(anio, mes, dia);
    }
    var categoryData = []

    category.map(function (row) {
        var dato = {};
        dato.horas = row[1] / 3600;
        dato.categoria = row[3];
        dato.rank = row[0];
        if (dato.horas > 0.2) {
            categoryData.push(dato)
        }
        return categoryData
    }
    )
    console.log("datos limpios", categoryData)

    daily.sort(function (a, b) {
        return convertirFecha(a.date) - convertirFecha(b.date);
    });
    function CustomTooltip({ active, payload, label }) {
        if (active) {
            var horas = daily.find(el => el.date === label).total_duration_formatted;
            var productividad = daily.find(el => el.date === label).productivity_pulse;
            return (
                <div className="custom-tooltip">
                    <p className="descripcion">{`${label}`}</p>
                    <p className="label">{`Work hours: ${horas} `}</p>
                    <p className="label">{` Performance: ${productividad}%`}</p>
                </div>
            );
        }

        return null;
    }
    const getDateDay = (date, locale) => {
        if (!locale) locale = 'en-US';
        var date = new Date(date);
        var dia = date.toLocaleString(locale, { weekday: 'short' });
        // console.log(dia)
        // var day = date.getDate();
        // var month = date.getMonth() + 1;
        return `${dia}`;
    }
    const porcentaje = (valor) => {
        return `${valor}%`
    }
    const hrs = (valor) => {
        return `${valor}h`
    }

    return (
        <div>
            <div className='titulo-descripcion'>Week Productivity  </div>
            <ResponsiveContainer minWidth={250} minHeight={200} maxWidth={"60%"}>
                <ComposedChart width={500}
                    height={400}
                    data={daily}
                    margin={{
                        top: 20,
                        right: 20,
                        bottom: 20,
                        left: 20,
                    }}>
                    {/* <LineChart data={daily}> */}
                    <Line yAxisId="right" type="monotone" dataKey="total_hours" stroke="#a5cfea" />
                    <CartesianGrid stroke="#f5f5f5" />
                    <Area type="monotone" dataKey="productivity_pulse" fill="#306fb8" stroke="#306fb8" />
                    <XAxis dataKey="date" angle={0} tickFormatter={getDateDay} stroke="#ffffff" />
                    <YAxis datakey="productivity_pulse" name="productividad" type="number" domain={[0, 100]} stroke="#306fb8" scale={"auto"} tickFormatter={porcentaje} />
                    <YAxis yAxisId="right" orientation="right" datakey="total_hours" name="horas" type="number" domain={[0, 24]} stroke="#a5cfea" scale={"auto"} tickFormatter={hrs} />
                    <Tooltip content={<CustomTooltip />} />
                    <Legend overlinePosition={-1} />
                    {/* </LineChart> */}
                </ComposedChart>
            </ResponsiveContainer>
            {categoryData.length > 1 &&
                <ResponsiveContainer minWidth={250} minHeight={200} maxWidth={"60%"}>
                    <RadarChart cx="50%" cy="50%" outerRadius="80%" data={categoryData}>
                        <PolarGrid />
                        <PolarAngleAxis dataKey="categoria" stroke="#ffffff" />
                        <PolarRadiusAxis stroke="#ffffff" />
                        <Radar name="Mike" dataKey="horas" stroke="#8884d8" fill="#306fb8" fillOpacity={0.6} />
                    </RadarChart>
                </ResponsiveContainer>
            }

        </div>
    );
}
export default Rescuetime;