const DataWeek = [
  {
    "id": 1650265200,
    "date": "2022-04-18",
    "productivity_pulse": 65,
    "very_productive_percentage": 17.2,
    "productive_percentage": 56.5,
    "neutral_percentage": 4.6,
    "distracting_percentage": 15.9,
    "very_distracting_percentage": 5.8,
    "all_productive_percentage": 73.6,
    "all_distracting_percentage": 21.7,
    "uncategorized_percentage": 1.9,
    "business_percentage": 0.9,
    "communication_and_scheduling_percentage": 20.5,
    "social_networking_percentage": 14.5,
    "design_and_composition_percentage": 14.4,
    "entertainment_percentage": 3.5,
    "news_percentage": 0.3,
    "software_development_percentage": 1.5,
    "reference_and_learning_percentage": 31.4,
    "shopping_percentage": 0.0,
    "utilities_percentage": 11.0,
    "total_hours": 11.24,
    "very_productive_hours": 1.93,
    "productive_hours": 6.35,
    "neutral_hours": 0.52,
    "distracting_hours": 1.79,
    "very_distracting_hours": 0.66,
    "all_productive_hours": 8.28,
    "all_distracting_hours": 2.44,
    "uncategorized_hours": 0.21,
    "business_hours": 0.1,
    "communication_and_scheduling_hours": 2.3,
    "social_networking_hours": 1.63,
    "design_and_composition_hours": 1.62,
    "entertainment_hours": 0.4,
    "news_hours": 0.04,
    "software_development_hours": 0.17,
    "reference_and_learning_hours": 3.53,
    "shopping_hours": 0.01,
    "utilities_hours": 1.24,
    "total_duration_formatted": "11h 14m",
    "very_productive_duration_formatted": "1h 55m",
    "productive_duration_formatted": "6h 20m",
    "neutral_duration_formatted": "31m 19s",
    "distracting_duration_formatted": "1h 47m",
    "very_distracting_duration_formatted": "39m 19s",
    "all_productive_duration_formatted": "8h 16m",
    "all_distracting_duration_formatted": "2h 26m",
    "uncategorized_duration_formatted": "12m 46s",
    "business_duration_formatted": "6m 11s",
    "communication_and_scheduling_duration_formatted": "2h 18m",
    "social_networking_duration_formatted": "1h 37m",
    "design_and_composition_duration_formatted": "1h 36m",
    "entertainment_duration_formatted": "23m 47s",
    "news_duration_formatted": "2m 13s",
    "software_development_duration_formatted": "10m 16s",
    "reference_and_learning_duration_formatted": "3h 31m",
    "shopping_duration_formatted": "18s",
    "utilities_duration_formatted": "1h 14m"
  },
  {
    "id": 1650178800,
    "date": "2022-04-17",
    "productivity_pulse": 57,
    "very_productive_percentage": 26.4,
    "productive_percentage": 26.9,
    "neutral_percentage": 5.4,
    "distracting_percentage": 32.8,
    "very_distracting_percentage": 8.4,
    "all_productive_percentage": 53.3,
    "all_distracting_percentage": 41.3,
    "uncategorized_percentage": 1.6,
    "business_percentage": 0.0,
    "communication_and_scheduling_percentage": 35.4,
    "social_networking_percentage": 1.3,
    "design_and_composition_percentage": 24.6,
    "entertainment_percentage": 7.8,
    "news_percentage": 0.5,
    "software_development_percentage": 0.0,
    "reference_and_learning_percentage": 15.6,
    "shopping_percentage": 0.0,
    "utilities_percentage": 13.1,
    "total_hours": 5.47,
    "very_productive_hours": 1.44,
    "productive_hours": 1.47,
    "neutral_hours": 0.3,
    "distracting_hours": 1.8,
    "very_distracting_hours": 0.46,
    "all_productive_hours": 2.92,
    "all_distracting_hours": 2.26,
    "uncategorized_hours": 0.09,
    "business_hours": 0.0,
    "communication_and_scheduling_hours": 1.94,
    "social_networking_hours": 0.07,
    "design_and_composition_hours": 1.35,
    "entertainment_hours": 0.43,
    "news_hours": 0.03,
    "software_development_hours": 0.0,
    "reference_and_learning_hours": 0.86,
    "shopping_hours": 0.0,
    "utilities_hours": 0.72,
    "total_duration_formatted": "5h 28m",
    "very_productive_duration_formatted": "1h 26m",
    "productive_duration_formatted": "1h 28m",
    "neutral_duration_formatted": "17m 47s",
    "distracting_duration_formatted": "1h 47m",
    "very_distracting_duration_formatted": "27m 39s",
    "all_productive_duration_formatted": "2h 54m",
    "all_distracting_duration_formatted": "2h 15m",
    "uncategorized_duration_formatted": "5m 16s",
    "business_duration_formatted": "no time",
    "communication_and_scheduling_duration_formatted": "1h 56m",
    "social_networking_duration_formatted": "4m 23s",
    "design_and_composition_duration_formatted": "1h 20m",
    "entertainment_duration_formatted": "25m 33s",
    "news_duration_formatted": "1m 30s",
    "software_development_duration_formatted": "no time",
    "reference_and_learning_duration_formatted": "51m 21s",
    "shopping_duration_formatted": "no time",
    "utilities_duration_formatted": "43m 6s"
  },
  {
    "id": 1650092400,
    "date": "2022-04-16",
    "productivity_pulse": 66,
    "very_productive_percentage": 12.0,
    "productive_percentage": 64.8,
    "neutral_percentage": 2.1,
    "distracting_percentage": 20.4,
    "very_distracting_percentage": 0.6,
    "all_productive_percentage": 76.9,
    "all_distracting_percentage": 21.0,
    "uncategorized_percentage": 0.7,
    "business_percentage": 0.0,
    "communication_and_scheduling_percentage": 22.8,
    "social_networking_percentage": 1.7,
    "design_and_composition_percentage": 12.0,
    "entertainment_percentage": 0.6,
    "news_percentage": 0.0,
    "software_development_percentage": 0.0,
    "reference_and_learning_percentage": 59.6,
    "shopping_percentage": 0.0,
    "utilities_percentage": 2.6,
    "total_hours": 4.6,
    "very_productive_hours": 0.55,
    "productive_hours": 2.98,
    "neutral_hours": 0.1,
    "distracting_hours": 0.94,
    "very_distracting_hours": 0.03,
    "all_productive_hours": 3.53,
    "all_distracting_hours": 0.97,
    "uncategorized_hours": 0.03,
    "business_hours": 0.0,
    "communication_and_scheduling_hours": 1.05,
    "social_networking_hours": 0.08,
    "design_and_composition_hours": 0.55,
    "entertainment_hours": 0.03,
    "news_hours": 0.0,
    "software_development_hours": 0.0,
    "reference_and_learning_hours": 2.74,
    "shopping_hours": 0.0,
    "utilities_hours": 0.12,
    "total_duration_formatted": "4h 35m",
    "very_productive_duration_formatted": "33m 7s",
    "productive_duration_formatted": "2h 58m",
    "neutral_duration_formatted": "5m 51s",
    "distracting_duration_formatted": "56m 19s",
    "very_distracting_duration_formatted": "1m 41s",
    "all_productive_duration_formatted": "3h 31m",
    "all_distracting_duration_formatted": "58m",
    "uncategorized_duration_formatted": "1m 55s",
    "business_duration_formatted": "no time",
    "communication_and_scheduling_duration_formatted": "1h 2m",
    "social_networking_duration_formatted": "4m 49s",
    "design_and_composition_duration_formatted": "33m 7s",
    "entertainment_duration_formatted": "1m 32s",
    "news_duration_formatted": "no time",
    "software_development_duration_formatted": "no time",
    "reference_and_learning_duration_formatted": "2h 44m",
    "shopping_duration_formatted": "no time",
    "utilities_duration_formatted": "7m 11s"
  },
  {
    "id": 1650006000,
    "date": "2022-04-15",
    "productivity_pulse": 56,
    "very_productive_percentage": 0.4,
    "productive_percentage": 61.8,
    "neutral_percentage": 9.9,
    "distracting_percentage": 18.1,
    "very_distracting_percentage": 9.9,
    "all_productive_percentage": 62.2,
    "all_distracting_percentage": 27.9,
    "uncategorized_percentage": 1.6,
    "business_percentage": 0.0,
    "communication_and_scheduling_percentage": 23.3,
    "social_networking_percentage": 2.6,
    "design_and_composition_percentage": 0.4,
    "entertainment_percentage": 15.2,
    "news_percentage": 0.0,
    "software_development_percentage": 0.0,
    "reference_and_learning_percentage": 35.6,
    "shopping_percentage": 0.0,
    "utilities_percentage": 21.3,
    "total_hours": 2.04,
    "very_productive_hours": 0.01,
    "productive_hours": 1.26,
    "neutral_hours": 0.2,
    "distracting_hours": 0.37,
    "very_distracting_hours": 0.2,
    "all_productive_hours": 1.27,
    "all_distracting_hours": 0.57,
    "uncategorized_hours": 0.03,
    "business_hours": 0.0,
    "communication_and_scheduling_hours": 0.47,
    "social_networking_hours": 0.05,
    "design_and_composition_hours": 0.01,
    "entertainment_hours": 0.31,
    "news_hours": 0.0,
    "software_development_hours": 0.0,
    "reference_and_learning_hours": 0.73,
    "shopping_hours": 0.0,
    "utilities_hours": 0.43,
    "total_duration_formatted": "2h 2m",
    "very_productive_duration_formatted": "29s",
    "productive_duration_formatted": "1h 15m",
    "neutral_duration_formatted": "12m 7s",
    "distracting_duration_formatted": "22m 5s",
    "very_distracting_duration_formatted": "12m 2s",
    "all_productive_duration_formatted": "1h 15m",
    "all_distracting_duration_formatted": "34m 7s",
    "uncategorized_duration_formatted": "1m 54s",
    "business_duration_formatted": "no time",
    "communication_and_scheduling_duration_formatted": "28m 26s",
    "social_networking_duration_formatted": "3m 9s",
    "design_and_composition_duration_formatted": "29s",
    "entertainment_duration_formatted": "18m 37s",
    "news_duration_formatted": "no time",
    "software_development_duration_formatted": "no time",
    "reference_and_learning_duration_formatted": "43m 31s",
    "shopping_duration_formatted": "no time",
    "utilities_duration_formatted": "26m 3s"
  },
  {
    "id": 1649919600,
    "date": "2022-04-14",
    "productivity_pulse": 69,
    "very_productive_percentage": 17.3,
    "productive_percentage": 60.5,
    "neutral_percentage": 10.7,
    "distracting_percentage": 6.3,
    "very_distracting_percentage": 5.2,
    "all_productive_percentage": 77.9,
    "all_distracting_percentage": 11.5,
    "uncategorized_percentage": 5.3,
    "business_percentage": 0.6,
    "communication_and_scheduling_percentage": 11.3,
    "social_networking_percentage": 9.9,
    "design_and_composition_percentage": 3.6,
    "entertainment_percentage": 4.1,
    "news_percentage": 0.0,
    "software_development_percentage": 10.8,
    "reference_and_learning_percentage": 45.4,
    "shopping_percentage": 0.9,
    "utilities_percentage": 8.1,
    "total_hours": 11.7,
    "very_productive_hours": 2.03,
    "productive_hours": 7.08,
    "neutral_hours": 1.25,
    "distracting_hours": 0.74,
    "very_distracting_hours": 0.6,
    "all_productive_hours": 9.11,
    "all_distracting_hours": 1.34,
    "uncategorized_hours": 0.62,
    "business_hours": 0.07,
    "communication_and_scheduling_hours": 1.32,
    "social_networking_hours": 1.16,
    "design_and_composition_hours": 0.43,
    "entertainment_hours": 0.48,
    "news_hours": 0.0,
    "software_development_hours": 1.26,
    "reference_and_learning_hours": 5.31,
    "shopping_hours": 0.1,
    "utilities_hours": 0.95,
    "total_duration_formatted": "11h 42m",
    "very_productive_duration_formatted": "2h 1m",
    "productive_duration_formatted": "7h 5m",
    "neutral_duration_formatted": "1h 14m",
    "distracting_duration_formatted": "44m 25s",
    "very_distracting_duration_formatted": "36m 16s",
    "all_productive_duration_formatted": "9h 6m",
    "all_distracting_duration_formatted": "1h 20m",
    "uncategorized_duration_formatted": "37m 7s",
    "business_duration_formatted": "4m 23s",
    "communication_and_scheduling_duration_formatted": "1h 19m",
    "social_networking_duration_formatted": "1h 9m",
    "design_and_composition_duration_formatted": "25m 34s",
    "entertainment_duration_formatted": "28m 46s",
    "news_duration_formatted": "no time",
    "software_development_duration_formatted": "1h 15m",
    "reference_and_learning_duration_formatted": "5h 18m",
    "shopping_duration_formatted": "6m 6s",
    "utilities_duration_formatted": "57m 3s"
  },
  {
    "id": 1649833200,
    "date": "2022-04-13",
    "productivity_pulse": 65,
    "very_productive_percentage": 20.3,
    "productive_percentage": 50.0,
    "neutral_percentage": 9.1,
    "distracting_percentage": 11.6,
    "very_distracting_percentage": 9.0,
    "all_productive_percentage": 70.3,
    "all_distracting_percentage": 20.6,
    "uncategorized_percentage": 4.4,
    "business_percentage": 1.7,
    "communication_and_scheduling_percentage": 24.5,
    "social_networking_percentage": 3.5,
    "design_and_composition_percentage": 0.1,
    "entertainment_percentage": 6.9,
    "news_percentage": 0.0,
    "software_development_percentage": 19.9,
    "reference_and_learning_percentage": 15.8,
    "shopping_percentage": 2.3,
    "utilities_percentage": 21.0,
    "total_hours": 9.57,
    "very_productive_hours": 1.95,
    "productive_hours": 4.78,
    "neutral_hours": 0.87,
    "distracting_hours": 1.11,
    "very_distracting_hours": 0.86,
    "all_productive_hours": 6.73,
    "all_distracting_hours": 1.97,
    "uncategorized_hours": 0.42,
    "business_hours": 0.16,
    "communication_and_scheduling_hours": 2.34,
    "social_networking_hours": 0.34,
    "design_and_composition_hours": 0.01,
    "entertainment_hours": 0.66,
    "news_hours": 0.0,
    "software_development_hours": 1.9,
    "reference_and_learning_hours": 1.51,
    "shopping_hours": 0.22,
    "utilities_hours": 2.01,
    "total_duration_formatted": "9h 34m",
    "very_productive_duration_formatted": "1h 56m",
    "productive_duration_formatted": "4h 46m",
    "neutral_duration_formatted": "52m 29s",
    "distracting_duration_formatted": "1h 6m",
    "very_distracting_duration_formatted": "51m 39s",
    "all_productive_duration_formatted": "6h 43m",
    "all_distracting_duration_formatted": "1h 58m",
    "uncategorized_duration_formatted": "25m 16s",
    "business_duration_formatted": "9m 39s",
    "communication_and_scheduling_duration_formatted": "2h 20m",
    "social_networking_duration_formatted": "20m 19s",
    "design_and_composition_duration_formatted": "31s",
    "entertainment_duration_formatted": "39m 42s",
    "news_duration_formatted": "no time",
    "software_development_duration_formatted": "1h 54m",
    "reference_and_learning_duration_formatted": "1h 30m",
    "shopping_duration_formatted": "12m 56s",
    "utilities_duration_formatted": "2h"
  },
  {
    "id": 1649746800,
    "date": "2022-04-12",
    "productivity_pulse": 67,
    "very_productive_percentage": 28.7,
    "productive_percentage": 43.6,
    "neutral_percentage": 4.4,
    "distracting_percentage": 15.2,
    "very_distracting_percentage": 8.1,
    "all_productive_percentage": 72.3,
    "all_distracting_percentage": 23.3,
    "uncategorized_percentage": 2.1,
    "business_percentage": 0.6,
    "communication_and_scheduling_percentage": 16.6,
    "social_networking_percentage": 3.5,
    "design_and_composition_percentage": 22.2,
    "entertainment_percentage": 7.0,
    "news_percentage": 0.0,
    "software_development_percentage": 5.9,
    "reference_and_learning_percentage": 36.7,
    "shopping_percentage": 0.0,
    "utilities_percentage": 5.4,
    "total_hours": 12.08,
    "very_productive_hours": 3.46,
    "productive_hours": 5.27,
    "neutral_hours": 0.53,
    "distracting_hours": 1.84,
    "very_distracting_hours": 0.97,
    "all_productive_hours": 8.73,
    "all_distracting_hours": 2.82,
    "uncategorized_hours": 0.25,
    "business_hours": 0.07,
    "communication_and_scheduling_hours": 2.0,
    "social_networking_hours": 0.42,
    "design_and_composition_hours": 2.69,
    "entertainment_hours": 0.84,
    "news_hours": 0.0,
    "software_development_hours": 0.72,
    "reference_and_learning_hours": 4.43,
    "shopping_hours": 0.0,
    "utilities_hours": 0.66,
    "total_duration_formatted": "12h 4m",
    "very_productive_duration_formatted": "3h 27m",
    "productive_duration_formatted": "5h 16m",
    "neutral_duration_formatted": "32m 4s",
    "distracting_duration_formatted": "1h 50m",
    "very_distracting_duration_formatted": "58m 24s",
    "all_productive_duration_formatted": "8h 43m",
    "all_distracting_duration_formatted": "2h 48m",
    "uncategorized_duration_formatted": "15m 11s",
    "business_duration_formatted": "4m 16s",
    "communication_and_scheduling_duration_formatted": "2h",
    "social_networking_duration_formatted": "25m 13s",
    "design_and_composition_duration_formatted": "2h 41m",
    "entertainment_duration_formatted": "50m 28s",
    "news_duration_formatted": "12s",
    "software_development_duration_formatted": "43m 1s",
    "reference_and_learning_duration_formatted": "4h 25m",
    "shopping_duration_formatted": "3s",
    "utilities_duration_formatted": "39m 28s"
  },
  {
    "id": 1649660400,
    "date": "2022-04-11",
    "productivity_pulse": 68,
    "very_productive_percentage": 31.5,
    "productive_percentage": 42.1,
    "neutral_percentage": 2.1,
    "distracting_percentage": 17.9,
    "very_distracting_percentage": 6.3,
    "all_productive_percentage": 73.7,
    "all_distracting_percentage": 24.2,
    "uncategorized_percentage": 0.0,
    "business_percentage": 1.9,
    "communication_and_scheduling_percentage": 19.2,
    "social_networking_percentage": 14.3,
    "design_and_composition_percentage": 18.0,
    "entertainment_percentage": 1.7,
    "news_percentage": 0.0,
    "software_development_percentage": 12.3,
    "reference_and_learning_percentage": 25.6,
    "shopping_percentage": 0.0,
    "utilities_percentage": 6.9,
    "total_hours": 11.17,
    "very_productive_hours": 3.52,
    "productive_hours": 4.71,
    "neutral_hours": 0.24,
    "distracting_hours": 2.0,
    "very_distracting_hours": 0.71,
    "all_productive_hours": 8.23,
    "all_distracting_hours": 2.7,
    "uncategorized_hours": 0.0,
    "business_hours": 0.21,
    "communication_and_scheduling_hours": 2.14,
    "social_networking_hours": 1.59,
    "design_and_composition_hours": 2.02,
    "entertainment_hours": 0.19,
    "news_hours": 0.0,
    "software_development_hours": 1.37,
    "reference_and_learning_hours": 2.86,
    "shopping_hours": 0.0,
    "utilities_hours": 0.78,
    "total_duration_formatted": "11h 10m",
    "very_productive_duration_formatted": "3h 31m",
    "productive_duration_formatted": "4h 42m",
    "neutral_duration_formatted": "14m 9s",
    "distracting_duration_formatted": "1h 59m",
    "very_distracting_duration_formatted": "42m 26s",
    "all_productive_duration_formatted": "8h 13m",
    "all_distracting_duration_formatted": "2h 42m",
    "uncategorized_duration_formatted": "13s",
    "business_duration_formatted": "12m 37s",
    "communication_and_scheduling_duration_formatted": "2h 8m",
    "social_networking_duration_formatted": "1h 35m",
    "design_and_composition_duration_formatted": "2h",
    "entertainment_duration_formatted": "11m 41s",
    "news_duration_formatted": "no time",
    "software_development_duration_formatted": "1h 22m",
    "reference_and_learning_duration_formatted": "2h 51m",
    "shopping_duration_formatted": "no time",
    "utilities_duration_formatted": "46m 31s"
  },
  {
    "id": 1649574000,
    "date": "2022-04-10",
    "productivity_pulse": 72,
    "very_productive_percentage": 27.8,
    "productive_percentage": 52.3,
    "neutral_percentage": 2.2,
    "distracting_percentage": 17.6,
    "very_distracting_percentage": 0.1,
    "all_productive_percentage": 80.1,
    "all_distracting_percentage": 17.7,
    "uncategorized_percentage": 0.2,
    "business_percentage": 0.1,
    "communication_and_scheduling_percentage": 28.3,
    "social_networking_percentage": 1.3,
    "design_and_composition_percentage": 26.8,
    "entertainment_percentage": 1.7,
    "news_percentage": 0.0,
    "software_development_percentage": 0.9,
    "reference_and_learning_percentage": 35.9,
    "shopping_percentage": 0.0,
    "utilities_percentage": 4.9,
    "total_hours": 8.7,
    "very_productive_hours": 2.42,
    "productive_hours": 4.55,
    "neutral_hours": 0.19,
    "distracting_hours": 1.53,
    "very_distracting_hours": 0.01,
    "all_productive_hours": 6.97,
    "all_distracting_hours": 1.54,
    "uncategorized_hours": 0.01,
    "business_hours": 0.01,
    "communication_and_scheduling_hours": 2.46,
    "social_networking_hours": 0.12,
    "design_and_composition_hours": 2.33,
    "entertainment_hours": 0.15,
    "news_hours": 0.0,
    "software_development_hours": 0.08,
    "reference_and_learning_hours": 3.12,
    "shopping_hours": 0.0,
    "utilities_hours": 0.42,
    "total_duration_formatted": "8h 41m",
    "very_productive_duration_formatted": "2h 25m",
    "productive_duration_formatted": "4h 32m",
    "neutral_duration_formatted": "11m 30s",
    "distracting_duration_formatted": "1h 31m",
    "very_distracting_duration_formatted": "20s",
    "all_productive_duration_formatted": "6h 58m",
    "all_distracting_duration_formatted": "1h 32m",
    "uncategorized_duration_formatted": "50s",
    "business_duration_formatted": "34s",
    "communication_and_scheduling_duration_formatted": "2h 27m",
    "social_networking_duration_formatted": "6m 56s",
    "design_and_composition_duration_formatted": "2h 19m",
    "entertainment_duration_formatted": "8m 54s",
    "news_duration_formatted": "no time",
    "software_development_duration_formatted": "4m 42s",
    "reference_and_learning_duration_formatted": "3h 7m",
    "shopping_duration_formatted": "no time",
    "utilities_duration_formatted": "25m 29s"
  },
  {
    "id": 1649487600,
    "date": "2022-04-09",
    "productivity_pulse": 69,
    "very_productive_percentage": 5.8,
    "productive_percentage": 78.1,
    "neutral_percentage": 6.6,
    "distracting_percentage": 8.4,
    "very_distracting_percentage": 1.1,
    "all_productive_percentage": 83.9,
    "all_distracting_percentage": 9.5,
    "uncategorized_percentage": 4.7,
    "business_percentage": 1.1,
    "communication_and_scheduling_percentage": 8.9,
    "social_networking_percentage": 1.1,
    "design_and_composition_percentage": 2.7,
    "entertainment_percentage": 0.4,
    "news_percentage": 0.0,
    "software_development_percentage": 0.5,
    "reference_and_learning_percentage": 79.9,
    "shopping_percentage": 0.1,
    "utilities_percentage": 0.5,
    "total_hours": 6.3,
    "very_productive_hours": 0.37,
    "productive_hours": 4.92,
    "neutral_hours": 0.42,
    "distracting_hours": 0.53,
    "very_distracting_hours": 0.07,
    "all_productive_hours": 5.28,
    "all_distracting_hours": 0.6,
    "uncategorized_hours": 0.3,
    "business_hours": 0.07,
    "communication_and_scheduling_hours": 0.56,
    "social_networking_hours": 0.07,
    "design_and_composition_hours": 0.17,
    "entertainment_hours": 0.03,
    "news_hours": 0.0,
    "software_development_hours": 0.03,
    "reference_and_learning_hours": 5.03,
    "shopping_hours": 0.01,
    "utilities_hours": 0.03,
    "total_duration_formatted": "6h 17m",
    "very_productive_duration_formatted": "21m 55s",
    "productive_duration_formatted": "4h 55m",
    "neutral_duration_formatted": "24m 56s",
    "distracting_duration_formatted": "31m 53s",
    "very_distracting_duration_formatted": "4m 2s",
    "all_productive_duration_formatted": "5h 16m",
    "all_distracting_duration_formatted": "35m 55s",
    "uncategorized_duration_formatted": "17m 49s",
    "business_duration_formatted": "4m 8s",
    "communication_and_scheduling_duration_formatted": "33m 29s",
    "social_networking_duration_formatted": "3m 59s",
    "design_and_composition_duration_formatted": "10m 13s",
    "entertainment_duration_formatted": "1m 31s",
    "news_duration_formatted": "11s",
    "software_development_duration_formatted": "1m 57s",
    "reference_and_learning_duration_formatted": "5h 1m",
    "shopping_duration_formatted": "29s",
    "utilities_duration_formatted": "2m 4s"
  },
  {
    "id": 1649401200,
    "date": "2022-04-08",
    "productivity_pulse": 84,
    "very_productive_percentage": 47.4,
    "productive_percentage": 45.8,
    "neutral_percentage": 5.1,
    "distracting_percentage": 0.0,
    "very_distracting_percentage": 1.7,
    "all_productive_percentage": 93.2,
    "all_distracting_percentage": 1.7,
    "uncategorized_percentage": 3.2,
    "business_percentage": 5.9,
    "communication_and_scheduling_percentage": 1.2,
    "social_networking_percentage": 1.6,
    "design_and_composition_percentage": 2.5,
    "entertainment_percentage": 1.0,
    "news_percentage": 0.0,
    "software_development_percentage": 32.2,
    "reference_and_learning_percentage": 50.0,
    "shopping_percentage": 1.4,
    "utilities_percentage": 1.0,
    "total_hours": 11.41,
    "very_productive_hours": 5.41,
    "productive_hours": 5.23,
    "neutral_hours": 0.58,
    "distracting_hours": 0.0,
    "very_distracting_hours": 0.19,
    "all_productive_hours": 10.63,
    "all_distracting_hours": 0.19,
    "uncategorized_hours": 0.37,
    "business_hours": 0.67,
    "communication_and_scheduling_hours": 0.13,
    "social_networking_hours": 0.18,
    "design_and_composition_hours": 0.29,
    "entertainment_hours": 0.11,
    "news_hours": 0.0,
    "software_development_hours": 3.67,
    "reference_and_learning_hours": 5.7,
    "shopping_hours": 0.16,
    "utilities_hours": 0.12,
    "total_duration_formatted": "11h 24m",
    "very_productive_duration_formatted": "5h 24m",
    "productive_duration_formatted": "5h 13m",
    "neutral_duration_formatted": "34m 58s",
    "distracting_duration_formatted": "1s",
    "very_distracting_duration_formatted": "11m 18s",
    "all_productive_duration_formatted": "10h 38m",
    "all_distracting_duration_formatted": "11m 19s",
    "uncategorized_duration_formatted": "22m 13s",
    "business_duration_formatted": "40m 10s",
    "communication_and_scheduling_duration_formatted": "8m 2s",
    "social_networking_duration_formatted": "11m 3s",
    "design_and_composition_duration_formatted": "17m 18s",
    "entertainment_duration_formatted": "6m 48s",
    "news_duration_formatted": "9s",
    "software_development_duration_formatted": "3h 40m",
    "reference_and_learning_duration_formatted": "5h 41m",
    "shopping_duration_formatted": "9m 18s",
    "utilities_duration_formatted": "7m 7s"
  },
  {
    "id": 1649314800,
    "date": "2022-04-07",
    "productivity_pulse": 80,
    "very_productive_percentage": 46.3,
    "productive_percentage": 38.5,
    "neutral_percentage": 10.7,
    "distracting_percentage": 0.0,
    "very_distracting_percentage": 4.6,
    "all_productive_percentage": 84.7,
    "all_distracting_percentage": 4.6,
    "uncategorized_percentage": 9.4,
    "business_percentage": 1.3,
    "communication_and_scheduling_percentage": 0.1,
    "social_networking_percentage": 4.8,
    "design_and_composition_percentage": 5.6,
    "entertainment_percentage": 4.1,
    "news_percentage": 0.9,
    "software_development_percentage": 39.3,
    "reference_and_learning_percentage": 24.4,
    "shopping_percentage": 0.0,
    "utilities_percentage": 10.1,
    "total_hours": 12.37,
    "very_productive_hours": 5.72,
    "productive_hours": 4.76,
    "neutral_hours": 1.32,
    "distracting_hours": 0.0,
    "very_distracting_hours": 0.57,
    "all_productive_hours": 10.48,
    "all_distracting_hours": 0.57,
    "uncategorized_hours": 1.17,
    "business_hours": 0.16,
    "communication_and_scheduling_hours": 0.02,
    "social_networking_hours": 0.59,
    "design_and_composition_hours": 0.69,
    "entertainment_hours": 0.51,
    "news_hours": 0.11,
    "software_development_hours": 4.87,
    "reference_and_learning_hours": 3.01,
    "shopping_hours": 0.0,
    "utilities_hours": 1.25,
    "total_duration_formatted": "12h 22m",
    "very_productive_duration_formatted": "5h 43m",
    "productive_duration_formatted": "4h 45m",
    "neutral_duration_formatted": "1h 19m",
    "distracting_duration_formatted": "11s",
    "very_distracting_duration_formatted": "34m 12s",
    "all_productive_duration_formatted": "10h 28m",
    "all_distracting_duration_formatted": "34m 23s",
    "uncategorized_duration_formatted": "1h 9m",
    "business_duration_formatted": "9m 22s",
    "communication_and_scheduling_duration_formatted": "58s",
    "social_networking_duration_formatted": "35m 21s",
    "design_and_composition_duration_formatted": "41m 31s",
    "entertainment_duration_formatted": "30m 21s",
    "news_duration_formatted": "6m 49s",
    "software_development_duration_formatted": "4h 52m",
    "reference_and_learning_duration_formatted": "3h",
    "shopping_duration_formatted": "no time",
    "utilities_duration_formatted": "1h 14m"
  },
  {
    "id": 1649228400,
    "date": "2022-04-06",
    "productivity_pulse": 80,
    "very_productive_percentage": 32.9,
    "productive_percentage": 62.7,
    "neutral_percentage": 1.9,
    "distracting_percentage": 0.0,
    "very_distracting_percentage": 2.4,
    "all_productive_percentage": 95.7,
    "all_distracting_percentage": 2.4,
    "uncategorized_percentage": 0.6,
    "business_percentage": 5.1,
    "communication_and_scheduling_percentage": 1.7,
    "social_networking_percentage": 4.0,
    "design_and_composition_percentage": 0.0,
    "entertainment_percentage": 1.5,
    "news_percentage": 0.1,
    "software_development_percentage": 17.7,
    "reference_and_learning_percentage": 59.1,
    "shopping_percentage": 1.8,
    "utilities_percentage": 8.3,
    "total_hours": 8.77,
    "very_productive_hours": 2.89,
    "productive_hours": 5.5,
    "neutral_hours": 0.17,
    "distracting_hours": 0.0,
    "very_distracting_hours": 0.21,
    "all_productive_hours": 8.39,
    "all_distracting_hours": 0.21,
    "uncategorized_hours": 0.06,
    "business_hours": 0.45,
    "communication_and_scheduling_hours": 0.15,
    "social_networking_hours": 0.35,
    "design_and_composition_hours": 0.0,
    "entertainment_hours": 0.13,
    "news_hours": 0.01,
    "software_development_hours": 1.55,
    "reference_and_learning_hours": 5.18,
    "shopping_hours": 0.16,
    "utilities_hours": 0.73,
    "total_duration_formatted": "8h 45m",
    "very_productive_duration_formatted": "2h 53m",
    "productive_duration_formatted": "5h 30m",
    "neutral_duration_formatted": "9m 58s",
    "distracting_duration_formatted": "no time",
    "very_distracting_duration_formatted": "12m 53s",
    "all_productive_duration_formatted": "8h 23m",
    "all_distracting_duration_formatted": "12m 53s",
    "uncategorized_duration_formatted": "3m 20s",
    "business_duration_formatted": "26m 52s",
    "communication_and_scheduling_duration_formatted": "9m 4s",
    "social_networking_duration_formatted": "21m 16s",
    "design_and_composition_duration_formatted": "8s",
    "entertainment_duration_formatted": "7m 52s",
    "news_duration_formatted": "31s",
    "software_development_duration_formatted": "1h 33m",
    "reference_and_learning_duration_formatted": "5h 10m",
    "shopping_duration_formatted": "9m 38s",
    "utilities_duration_formatted": "43m 36s"
  },
  {
    "id": 1649142000,
    "date": "2022-04-05",
    "productivity_pulse": 73,
    "very_productive_percentage": 20.8,
    "productive_percentage": 64.8,
    "neutral_percentage": 8.6,
    "distracting_percentage": 0.0,
    "very_distracting_percentage": 5.9,
    "all_productive_percentage": 85.5,
    "all_distracting_percentage": 5.9,
    "uncategorized_percentage": 5.0,
    "business_percentage": 10.8,
    "communication_and_scheduling_percentage": 0.3,
    "social_networking_percentage": 7.6,
    "design_and_composition_percentage": 5.5,
    "entertainment_percentage": 3.4,
    "news_percentage": 0.0,
    "software_development_percentage": 2.3,
    "reference_and_learning_percentage": 54.5,
    "shopping_percentage": 5.9,
    "utilities_percentage": 4.6,
    "total_hours": 3.98,
    "very_productive_hours": 0.83,
    "productive_hours": 2.58,
    "neutral_hours": 0.34,
    "distracting_hours": 0.0,
    "very_distracting_hours": 0.23,
    "all_productive_hours": 3.4,
    "all_distracting_hours": 0.23,
    "uncategorized_hours": 0.2,
    "business_hours": 0.43,
    "communication_and_scheduling_hours": 0.01,
    "social_networking_hours": 0.3,
    "design_and_composition_hours": 0.22,
    "entertainment_hours": 0.14,
    "news_hours": 0.0,
    "software_development_hours": 0.09,
    "reference_and_learning_hours": 2.17,
    "shopping_hours": 0.23,
    "utilities_hours": 0.18,
    "total_duration_formatted": "3h 58m",
    "very_productive_duration_formatted": "49m 31s",
    "productive_duration_formatted": "2h 34m",
    "neutral_duration_formatted": "20m 31s",
    "distracting_duration_formatted": "no time",
    "very_distracting_duration_formatted": "14m 2s",
    "all_productive_duration_formatted": "3h 24m",
    "all_distracting_duration_formatted": "14m 2s",
    "uncategorized_duration_formatted": "12m 1s",
    "business_duration_formatted": "25m 49s",
    "communication_and_scheduling_duration_formatted": "48s",
    "social_networking_duration_formatted": "18m 6s",
    "design_and_composition_duration_formatted": "13m 8s",
    "entertainment_duration_formatted": "8m 8s",
    "news_duration_formatted": "no time",
    "software_development_duration_formatted": "5m 34s",
    "reference_and_learning_duration_formatted": "2h 10m",
    "shopping_duration_formatted": "14m 2s",
    "utilities_duration_formatted": "10m 55s"
  },
  {
    "id": 1649055600,
    "date": "2022-04-04",
    "productivity_pulse": 74,
    "very_productive_percentage": 39.4,
    "productive_percentage": 42.6,
    "neutral_percentage": 3.9,
    "distracting_percentage": 3.4,
    "very_distracting_percentage": 10.6,
    "all_productive_percentage": 82.1,
    "all_distracting_percentage": 14.0,
    "uncategorized_percentage": 2.9,
    "business_percentage": 4.1,
    "communication_and_scheduling_percentage": 6.0,
    "social_networking_percentage": 3.0,
    "design_and_composition_percentage": 6.9,
    "entertainment_percentage": 9.3,
    "news_percentage": 0.4,
    "software_development_percentage": 26.9,
    "reference_and_learning_percentage": 31.6,
    "shopping_percentage": 0.0,
    "utilities_percentage": 8.9,
    "total_hours": 12.17,
    "very_productive_hours": 4.8,
    "productive_hours": 5.19,
    "neutral_hours": 0.48,
    "distracting_hours": 0.41,
    "very_distracting_hours": 1.29,
    "all_productive_hours": 9.99,
    "all_distracting_hours": 1.7,
    "uncategorized_hours": 0.36,
    "business_hours": 0.5,
    "communication_and_scheduling_hours": 0.73,
    "social_networking_hours": 0.36,
    "design_and_composition_hours": 0.84,
    "entertainment_hours": 1.13,
    "news_hours": 0.05,
    "software_development_hours": 3.27,
    "reference_and_learning_hours": 3.84,
    "shopping_hours": 0.0,
    "utilities_hours": 1.09,
    "total_duration_formatted": "12h 10m",
    "very_productive_duration_formatted": "4h 48m",
    "productive_duration_formatted": "5h 11m",
    "neutral_duration_formatted": "28m 37s",
    "distracting_duration_formatted": "24m 41s",
    "very_distracting_duration_formatted": "1h 17m",
    "all_productive_duration_formatted": "9h 59m",
    "all_distracting_duration_formatted": "1h 42m",
    "uncategorized_duration_formatted": "21m 32s",
    "business_duration_formatted": "29m 56s",
    "communication_and_scheduling_duration_formatted": "43m 46s",
    "social_networking_duration_formatted": "21m 43s",
    "design_and_composition_duration_formatted": "50m 30s",
    "entertainment_duration_formatted": "1h 7m",
    "news_duration_formatted": "2m 56s",
    "software_development_duration_formatted": "3h 16m",
    "reference_and_learning_duration_formatted": "3h 50m",
    "shopping_duration_formatted": "no time",
    "utilities_duration_formatted": "1h 5m"
  }
]
export default DataWeek;