const DataWeek = [
  {
    "id": 1649228400,
    "date": "2022-04-06",
    "productivity_pulse": 80,
    "very_productive_percentage": 32.9,
    "productive_percentage": 62.7,
    "neutral_percentage": 1.9,
    "distracting_percentage": 0.0,
    "very_distracting_percentage": 2.4,
    "all_productive_percentage": 95.7,
    "all_distracting_percentage": 2.4,
    "uncategorized_percentage": 0.6,
    "business_percentage": 5.1,
    "communication_and_scheduling_percentage": 1.7,
    "social_networking_percentage": 4.0,
    "design_and_composition_percentage": 0.0,
    "entertainment_percentage": 1.5,
    "news_percentage": 0.1,
    "software_development_percentage": 17.7,
    "reference_and_learning_percentage": 59.1,
    "shopping_percentage": 1.8,
    "utilities_percentage": 8.3,
    "total_hours": 8.77,
    "very_productive_hours": 2.89,
    "productive_hours": 5.5,
    "neutral_hours": 0.17,
    "distracting_hours": 0.0,
    "very_distracting_hours": 0.21,
    "all_productive_hours": 8.39,
    "all_distracting_hours": 0.21,
    "uncategorized_hours": 0.06,
    "business_hours": 0.45,
    "communication_and_scheduling_hours": 0.15,
    "social_networking_hours": 0.35,
    "design_and_composition_hours": 0.0,
    "entertainment_hours": 0.13,
    "news_hours": 0.01,
    "software_development_hours": 1.55,
    "reference_and_learning_hours": 5.18,
    "shopping_hours": 0.16,
    "utilities_hours": 0.73,
    "total_duration_formatted": "8h 45m",
    "very_productive_duration_formatted": "2h 53m",
    "productive_duration_formatted": "5h 30m",
    "neutral_duration_formatted": "9m 58s",
    "distracting_duration_formatted": "no time",
    "very_distracting_duration_formatted": "12m 53s",
    "all_productive_duration_formatted": "8h 23m",
    "all_distracting_duration_formatted": "12m 53s",
    "uncategorized_duration_formatted": "3m 20s",
    "business_duration_formatted": "26m 52s",
    "communication_and_scheduling_duration_formatted": "9m 4s",
    "social_networking_duration_formatted": "21m 16s",
    "design_and_composition_duration_formatted": "8s",
    "entertainment_duration_formatted": "7m 52s",
    "news_duration_formatted": "31s",
    "software_development_duration_formatted": "1h 33m",
    "reference_and_learning_duration_formatted": "5h 10m",
    "shopping_duration_formatted": "9m 38s",
    "utilities_duration_formatted": "43m 36s"
  },
  {
    "id": 1649142000,
    "date": "2022-04-05",
    "productivity_pulse": 73,
    "very_productive_percentage": 20.8,
    "productive_percentage": 64.8,
    "neutral_percentage": 8.6,
    "distracting_percentage": 0.0,
    "very_distracting_percentage": 5.9,
    "all_productive_percentage": 85.5,
    "all_distracting_percentage": 5.9,
    "uncategorized_percentage": 5.0,
    "business_percentage": 10.8,
    "communication_and_scheduling_percentage": 0.3,
    "social_networking_percentage": 7.6,
    "design_and_composition_percentage": 5.5,
    "entertainment_percentage": 3.4,
    "news_percentage": 0.0,
    "software_development_percentage": 2.3,
    "reference_and_learning_percentage": 54.5,
    "shopping_percentage": 5.9,
    "utilities_percentage": 4.6,
    "total_hours": 3.98,
    "very_productive_hours": 0.83,
    "productive_hours": 2.58,
    "neutral_hours": 0.34,
    "distracting_hours": 0.0,
    "very_distracting_hours": 0.23,
    "all_productive_hours": 3.4,
    "all_distracting_hours": 0.23,
    "uncategorized_hours": 0.2,
    "business_hours": 0.43,
    "communication_and_scheduling_hours": 0.01,
    "social_networking_hours": 0.3,
    "design_and_composition_hours": 0.22,
    "entertainment_hours": 0.14,
    "news_hours": 0.0,
    "software_development_hours": 0.09,
    "reference_and_learning_hours": 2.17,
    "shopping_hours": 0.23,
    "utilities_hours": 0.18,
    "total_duration_formatted": "3h 58m",
    "very_productive_duration_formatted": "49m 31s",
    "productive_duration_formatted": "2h 34m",
    "neutral_duration_formatted": "20m 31s",
    "distracting_duration_formatted": "no time",
    "very_distracting_duration_formatted": "14m 2s",
    "all_productive_duration_formatted": "3h 24m",
    "all_distracting_duration_formatted": "14m 2s",
    "uncategorized_duration_formatted": "12m 1s",
    "business_duration_formatted": "25m 49s",
    "communication_and_scheduling_duration_formatted": "48s",
    "social_networking_duration_formatted": "18m 6s",
    "design_and_composition_duration_formatted": "13m 8s",
    "entertainment_duration_formatted": "8m 8s",
    "news_duration_formatted": "no time",
    "software_development_duration_formatted": "5m 34s",
    "reference_and_learning_duration_formatted": "2h 10m",
    "shopping_duration_formatted": "14m 2s",
    "utilities_duration_formatted": "10m 55s"
  },
  {
    "id": 1649055600,
    "date": "2022-04-04",
    "productivity_pulse": 74,
    "very_productive_percentage": 39.4,
    "productive_percentage": 42.6,
    "neutral_percentage": 3.9,
    "distracting_percentage": 3.4,
    "very_distracting_percentage": 10.6,
    "all_productive_percentage": 82.1,
    "all_distracting_percentage": 14.0,
    "uncategorized_percentage": 2.9,
    "business_percentage": 4.1,
    "communication_and_scheduling_percentage": 6.0,
    "social_networking_percentage": 3.0,
    "design_and_composition_percentage": 6.9,
    "entertainment_percentage": 9.3,
    "news_percentage": 0.4,
    "software_development_percentage": 26.9,
    "reference_and_learning_percentage": 31.6,
    "shopping_percentage": 0.0,
    "utilities_percentage": 8.9,
    "total_hours": 12.17,
    "very_productive_hours": 4.8,
    "productive_hours": 5.19,
    "neutral_hours": 0.48,
    "distracting_hours": 0.41,
    "very_distracting_hours": 1.29,
    "all_productive_hours": 9.99,
    "all_distracting_hours": 1.7,
    "uncategorized_hours": 0.36,
    "business_hours": 0.5,
    "communication_and_scheduling_hours": 0.73,
    "social_networking_hours": 0.36,
    "design_and_composition_hours": 0.84,
    "entertainment_hours": 1.13,
    "news_hours": 0.05,
    "software_development_hours": 3.27,
    "reference_and_learning_hours": 3.84,
    "shopping_hours": 0.0,
    "utilities_hours": 1.09,
    "total_duration_formatted": "12h 10m",
    "very_productive_duration_formatted": "4h 48m",
    "productive_duration_formatted": "5h 11m",
    "neutral_duration_formatted": "28m 37s",
    "distracting_duration_formatted": "24m 41s",
    "very_distracting_duration_formatted": "1h 17m",
    "all_productive_duration_formatted": "9h 59m",
    "all_distracting_duration_formatted": "1h 42m",
    "uncategorized_duration_formatted": "21m 32s",
    "business_duration_formatted": "29m 56s",
    "communication_and_scheduling_duration_formatted": "43m 46s",
    "social_networking_duration_formatted": "21m 43s",
    "design_and_composition_duration_formatted": "50m 30s",
    "entertainment_duration_formatted": "1h 7m",
    "news_duration_formatted": "2m 56s",
    "software_development_duration_formatted": "3h 16m",
    "reference_and_learning_duration_formatted": "3h 50m",
    "shopping_duration_formatted": "no time",
    "utilities_duration_formatted": "1h 5m"
  },
  {
    "id": 1648969200,
    "date": "2022-04-03",
    "productivity_pulse": 61,
    "very_productive_percentage": 12.5,
    "productive_percentage": 54.9,
    "neutral_percentage": 2.7,
    "distracting_percentage": 24.6,
    "very_distracting_percentage": 5.3,
    "all_productive_percentage": 67.4,
    "all_distracting_percentage": 29.9,
    "uncategorized_percentage": 0.6,
    "business_percentage": 4.4,
    "communication_and_scheduling_percentage": 60.3,
    "social_networking_percentage": 4.3,
    "design_and_composition_percentage": 5.2,
    "entertainment_percentage": 2.3,
    "news_percentage": 0.0,
    "software_development_percentage": 2.2,
    "reference_and_learning_percentage": 12.1,
    "shopping_percentage": 0.2,
    "utilities_percentage": 8.4,
    "total_hours": 6.23,
    "very_productive_hours": 0.78,
    "productive_hours": 3.42,
    "neutral_hours": 0.17,
    "distracting_hours": 1.53,
    "very_distracting_hours": 0.33,
    "all_productive_hours": 4.2,
    "all_distracting_hours": 1.86,
    "uncategorized_hours": 0.04,
    "business_hours": 0.28,
    "communication_and_scheduling_hours": 3.76,
    "social_networking_hours": 0.27,
    "design_and_composition_hours": 0.32,
    "entertainment_hours": 0.14,
    "news_hours": 0.0,
    "software_development_hours": 0.14,
    "reference_and_learning_hours": 0.75,
    "shopping_hours": 0.01,
    "utilities_hours": 0.52,
    "total_duration_formatted": "6h 13m",
    "very_productive_duration_formatted": "46m 54s",
    "productive_duration_formatted": "3h 25m",
    "neutral_duration_formatted": "9m 56s",
    "distracting_duration_formatted": "1h 31m",
    "very_distracting_duration_formatted": "19m 55s",
    "all_productive_duration_formatted": "4h 12m",
    "all_distracting_duration_formatted": "1h 51m",
    "uncategorized_duration_formatted": "2m 25s",
    "business_duration_formatted": "16m 36s",
    "communication_and_scheduling_duration_formatted": "3h 45m",
    "social_networking_duration_formatted": "16m 3s",
    "design_and_composition_duration_formatted": "19m 22s",
    "entertainment_duration_formatted": "8m 33s",
    "news_duration_formatted": "no time",
    "software_development_duration_formatted": "8m 11s",
    "reference_and_learning_duration_formatted": "45m 17s",
    "shopping_duration_formatted": "47s",
    "utilities_duration_formatted": "31m 15s"
  },
  {
    "id": 1648882800,
    "date": "2022-04-02",
    "productivity_pulse": 35,
    "very_productive_percentage": 6.3,
    "productive_percentage": 21.0,
    "neutral_percentage": 7.0,
    "distracting_percentage": 38.4,
    "very_distracting_percentage": 27.3,
    "all_productive_percentage": 27.3,
    "all_distracting_percentage": 65.7,
    "uncategorized_percentage": 1.3,
    "business_percentage": 1.0,
    "communication_and_scheduling_percentage": 37.0,
    "social_networking_percentage": 23.8,
    "design_and_composition_percentage": 6.3,
    "entertainment_percentage": 11.8,
    "news_percentage": 0.8,
    "software_development_percentage": 0.0,
    "reference_and_learning_percentage": 6.8,
    "shopping_percentage": 0.0,
    "utilities_percentage": 11.2,
    "total_hours": 5.26,
    "very_productive_hours": 0.33,
    "productive_hours": 1.11,
    "neutral_hours": 0.37,
    "distracting_hours": 2.02,
    "very_distracting_hours": 1.44,
    "all_productive_hours": 1.44,
    "all_distracting_hours": 3.46,
    "uncategorized_hours": 0.07,
    "business_hours": 0.05,
    "communication_and_scheduling_hours": 1.95,
    "social_networking_hours": 1.25,
    "design_and_composition_hours": 0.33,
    "entertainment_hours": 0.62,
    "news_hours": 0.04,
    "software_development_hours": 0.0,
    "reference_and_learning_hours": 0.36,
    "shopping_hours": 0.0,
    "utilities_hours": 0.59,
    "total_duration_formatted": "5h 15m",
    "very_productive_duration_formatted": "19m 52s",
    "productive_duration_formatted": "1h 6m",
    "neutral_duration_formatted": "22m 14s",
    "distracting_duration_formatted": "2h 1m",
    "very_distracting_duration_formatted": "1h 26m",
    "all_productive_duration_formatted": "1h 26m",
    "all_distracting_duration_formatted": "3h 27m",
    "uncategorized_duration_formatted": "4m 10s",
    "business_duration_formatted": "3m 5s",
    "communication_and_scheduling_duration_formatted": "1h 56m",
    "social_networking_duration_formatted": "1h 15m",
    "design_and_composition_duration_formatted": "19m 47s",
    "entertainment_duration_formatted": "37m 20s",
    "news_duration_formatted": "2m 33s",
    "software_development_duration_formatted": "no time",
    "reference_and_learning_duration_formatted": "21m 33s",
    "shopping_duration_formatted": "8s",
    "utilities_duration_formatted": "35m 24s"
  },
  {
    "id": 1648796400,
    "date": "2022-04-01",
    "productivity_pulse": 73,
    "very_productive_percentage": 37.6,
    "productive_percentage": 40.3,
    "neutral_percentage": 2.4,
    "distracting_percentage": 17.3,
    "very_distracting_percentage": 2.4,
    "all_productive_percentage": 77.9,
    "all_distracting_percentage": 19.7,
    "uncategorized_percentage": 0.2,
    "business_percentage": 4.3,
    "communication_and_scheduling_percentage": 20.9,
    "social_networking_percentage": 6.3,
    "design_and_composition_percentage": 2.4,
    "entertainment_percentage": 2.4,
    "news_percentage": 0.2,
    "software_development_percentage": 30.6,
    "reference_and_learning_percentage": 17.0,
    "shopping_percentage": 0.0,
    "utilities_percentage": 15.8,
    "total_hours": 14.6,
    "very_productive_hours": 5.49,
    "productive_hours": 5.89,
    "neutral_hours": 0.35,
    "distracting_hours": 2.53,
    "very_distracting_hours": 0.35,
    "all_productive_hours": 11.38,
    "all_distracting_hours": 2.87,
    "uncategorized_hours": 0.03,
    "business_hours": 0.63,
    "communication_and_scheduling_hours": 3.05,
    "social_networking_hours": 0.91,
    "design_and_composition_hours": 0.35,
    "entertainment_hours": 0.35,
    "news_hours": 0.04,
    "software_development_hours": 4.46,
    "reference_and_learning_hours": 2.48,
    "shopping_hours": 0.0,
    "utilities_hours": 2.3,
    "total_duration_formatted": "14h 36m",
    "very_productive_duration_formatted": "5h 29m",
    "productive_duration_formatted": "5h 53m",
    "neutral_duration_formatted": "20m 51s",
    "distracting_duration_formatted": "2h 31m",
    "very_distracting_duration_formatted": "20m 48s",
    "all_productive_duration_formatted": "11h 22m",
    "all_distracting_duration_formatted": "2h 52m",
    "uncategorized_duration_formatted": "1m 50s",
    "business_duration_formatted": "37m 30s",
    "communication_and_scheduling_duration_formatted": "3h 2m",
    "social_networking_duration_formatted": "54m 49s",
    "design_and_composition_duration_formatted": "21m 6s",
    "entertainment_duration_formatted": "21m 14s",
    "news_duration_formatted": "2m 7s",
    "software_development_duration_formatted": "4h 27m",
    "reference_and_learning_duration_formatted": "2h 28m",
    "shopping_duration_formatted": "2s",
    "utilities_duration_formatted": "2h 18m"
  },
  {
    "id": 1648710000,
    "date": "2022-03-31",
    "productivity_pulse": 77,
    "very_productive_percentage": 40.2,
    "productive_percentage": 46.0,
    "neutral_percentage": 2.7,
    "distracting_percentage": 6.2,
    "very_distracting_percentage": 5.0,
    "all_productive_percentage": 86.2,
    "all_distracting_percentage": 11.1,
    "uncategorized_percentage": 1.0,
    "business_percentage": 2.9,
    "communication_and_scheduling_percentage": 9.0,
    "social_networking_percentage": 7.3,
    "design_and_composition_percentage": 13.6,
    "entertainment_percentage": 2.7,
    "news_percentage": 0.3,
    "software_development_percentage": 23.7,
    "reference_and_learning_percentage": 31.8,
    "shopping_percentage": 0.0,
    "utilities_percentage": 7.7,
    "total_hours": 26.69,
    "very_productive_hours": 10.73,
    "productive_hours": 12.28,
    "neutral_hours": 0.71,
    "distracting_hours": 1.64,
    "very_distracting_hours": 1.33,
    "all_productive_hours": 23.01,
    "all_distracting_hours": 2.97,
    "uncategorized_hours": 0.25,
    "business_hours": 0.77,
    "communication_and_scheduling_hours": 2.41,
    "social_networking_hours": 1.95,
    "design_and_composition_hours": 3.64,
    "entertainment_hours": 0.72,
    "news_hours": 0.08,
    "software_development_hours": 6.33,
    "reference_and_learning_hours": 8.48,
    "shopping_hours": 0.01,
    "utilities_hours": 2.06,
    "total_duration_formatted": "26h 41m",
    "very_productive_duration_formatted": "10h 43m",
    "productive_duration_formatted": "12h 17m",
    "neutral_duration_formatted": "42m 38s",
    "distracting_duration_formatted": "1h 38m",
    "very_distracting_duration_formatted": "1h 19m",
    "all_productive_duration_formatted": "23h",
    "all_distracting_duration_formatted": "2h 58m",
    "uncategorized_duration_formatted": "15m 13s",
    "business_duration_formatted": "46m 21s",
    "communication_and_scheduling_duration_formatted": "2h 24m",
    "social_networking_duration_formatted": "1h 57m",
    "design_and_composition_duration_formatted": "3h 38m",
    "entertainment_duration_formatted": "42m 58s",
    "news_duration_formatted": "4m 36s",
    "software_development_duration_formatted": "6h 20m",
    "reference_and_learning_duration_formatted": "8h 28m",
    "shopping_duration_formatted": "25s",
    "utilities_duration_formatted": "2h 3m"
  },
  {
    "id": 1648623600,
    "date": "2022-03-30",
    "productivity_pulse": 81,
    "very_productive_percentage": 47.1,
    "productive_percentage": 41.1,
    "neutral_percentage": 3.5,
    "distracting_percentage": 7.0,
    "very_distracting_percentage": 1.3,
    "all_productive_percentage": 88.2,
    "all_distracting_percentage": 8.3,
    "uncategorized_percentage": 1.4,
    "business_percentage": 7.5,
    "communication_and_scheduling_percentage": 7.0,
    "social_networking_percentage": 10.4,
    "design_and_composition_percentage": 2.1,
    "entertainment_percentage": 1.3,
    "news_percentage": 0.4,
    "software_development_percentage": 37.3,
    "reference_and_learning_percentage": 26.7,
    "shopping_percentage": 0.2,
    "utilities_percentage": 5.7,
    "total_hours": 23.49,
    "very_productive_hours": 11.07,
    "productive_hours": 9.66,
    "neutral_hours": 0.81,
    "distracting_hours": 1.65,
    "very_distracting_hours": 0.3,
    "all_productive_hours": 20.73,
    "all_distracting_hours": 1.95,
    "uncategorized_hours": 0.33,
    "business_hours": 1.77,
    "communication_and_scheduling_hours": 1.65,
    "social_networking_hours": 2.44,
    "design_and_composition_hours": 0.49,
    "entertainment_hours": 0.3,
    "news_hours": 0.09,
    "software_development_hours": 8.76,
    "reference_and_learning_hours": 6.28,
    "shopping_hours": 0.05,
    "utilities_hours": 1.33,
    "total_duration_formatted": "23h 29m",
    "very_productive_duration_formatted": "11h 4m",
    "productive_duration_formatted": "9h 39m",
    "neutral_duration_formatted": "48m 43s",
    "distracting_duration_formatted": "1h 38m",
    "very_distracting_duration_formatted": "18m 13s",
    "all_productive_duration_formatted": "20h 43m",
    "all_distracting_duration_formatted": "1h 57m",
    "uncategorized_duration_formatted": "20m 2s",
    "business_duration_formatted": "1h 46m",
    "communication_and_scheduling_duration_formatted": "1h 39m",
    "social_networking_duration_formatted": "2h 26m",
    "design_and_composition_duration_formatted": "29m 18s",
    "entertainment_duration_formatted": "18m 13s",
    "news_duration_formatted": "5m 12s",
    "software_development_duration_formatted": "8h 45m",
    "reference_and_learning_duration_formatted": "6h 16m",
    "shopping_duration_formatted": "3m",
    "utilities_duration_formatted": "1h 19m"
  },
  {
    "id": 1648537200,
    "date": "2022-03-29",
    "productivity_pulse": 80,
    "very_productive_percentage": 52.2,
    "productive_percentage": 32.2,
    "neutral_percentage": 2.6,
    "distracting_percentage": 11.3,
    "very_distracting_percentage": 1.6,
    "all_productive_percentage": 84.4,
    "all_distracting_percentage": 12.9,
    "uncategorized_percentage": 0.5,
    "business_percentage": 1.4,
    "communication_and_scheduling_percentage": 8.6,
    "social_networking_percentage": 4.8,
    "design_and_composition_percentage": 5.2,
    "entertainment_percentage": 4.2,
    "news_percentage": 0.4,
    "software_development_percentage": 45.8,
    "reference_and_learning_percentage": 19.6,
    "shopping_percentage": 0.0,
    "utilities_percentage": 9.5,
    "total_hours": 21.76,
    "very_productive_hours": 11.36,
    "productive_hours": 7.02,
    "neutral_hours": 0.57,
    "distracting_hours": 2.47,
    "very_distracting_hours": 0.35,
    "all_productive_hours": 18.37,
    "all_distracting_hours": 2.82,
    "uncategorized_hours": 0.11,
    "business_hours": 0.31,
    "communication_and_scheduling_hours": 1.86,
    "social_networking_hours": 1.04,
    "design_and_composition_hours": 1.13,
    "entertainment_hours": 0.91,
    "news_hours": 0.1,
    "software_development_hours": 9.97,
    "reference_and_learning_hours": 4.25,
    "shopping_hours": 0.01,
    "utilities_hours": 2.07,
    "total_duration_formatted": "21h 45m",
    "very_productive_duration_formatted": "11h 21m",
    "productive_duration_formatted": "7h",
    "neutral_duration_formatted": "34m 7s",
    "distracting_duration_formatted": "2h 27m",
    "very_distracting_duration_formatted": "21m 5s",
    "all_productive_duration_formatted": "18h 22m",
    "all_distracting_duration_formatted": "2h 48m",
    "uncategorized_duration_formatted": "6m 26s",
    "business_duration_formatted": "18m 18s",
    "communication_and_scheduling_duration_formatted": "1h 51m",
    "social_networking_duration_formatted": "1h 2m",
    "design_and_composition_duration_formatted": "1h 7m",
    "entertainment_duration_formatted": "54m 27s",
    "news_duration_formatted": "5m 44s",
    "software_development_duration_formatted": "9h 58m",
    "reference_and_learning_duration_formatted": "4h 15m",
    "shopping_duration_formatted": "30s",
    "utilities_duration_formatted": "2h 4m"
  },
  {
    "id": 1648450800,
    "date": "2022-03-28",
    "productivity_pulse": 73,
    "very_productive_percentage": 46.5,
    "productive_percentage": 28.8,
    "neutral_percentage": 3.3,
    "distracting_percentage": 15.2,
    "very_distracting_percentage": 6.2,
    "all_productive_percentage": 75.3,
    "all_distracting_percentage": 21.4,
    "uncategorized_percentage": 0.4,
    "business_percentage": 1.6,
    "communication_and_scheduling_percentage": 14.2,
    "social_networking_percentage": 9.8,
    "design_and_composition_percentage": 0.3,
    "entertainment_percentage": 4.8,
    "news_percentage": 0.6,
    "software_development_percentage": 44.7,
    "reference_and_learning_percentage": 9.1,
    "shopping_percentage": 0.1,
    "utilities_percentage": 14.3,
    "total_hours": 13.38,
    "very_productive_hours": 6.23,
    "productive_hours": 3.85,
    "neutral_hours": 0.44,
    "distracting_hours": 2.03,
    "very_distracting_hours": 0.83,
    "all_productive_hours": 10.08,
    "all_distracting_hours": 2.86,
    "uncategorized_hours": 0.05,
    "business_hours": 0.22,
    "communication_and_scheduling_hours": 1.9,
    "social_networking_hours": 1.31,
    "design_and_composition_hours": 0.04,
    "entertainment_hours": 0.65,
    "news_hours": 0.08,
    "software_development_hours": 5.98,
    "reference_and_learning_hours": 1.22,
    "shopping_hours": 0.02,
    "utilities_hours": 1.92,
    "total_duration_formatted": "13h 23m",
    "very_productive_duration_formatted": "6h 13m",
    "productive_duration_formatted": "3h 51m",
    "neutral_duration_formatted": "26m 28s",
    "distracting_duration_formatted": "2h 1m",
    "very_distracting_duration_formatted": "49m 47s",
    "all_productive_duration_formatted": "10h 4m",
    "all_distracting_duration_formatted": "2h 51m",
    "uncategorized_duration_formatted": "2m 58s",
    "business_duration_formatted": "13m 4s",
    "communication_and_scheduling_duration_formatted": "1h 54m",
    "social_networking_duration_formatted": "1h 18m",
    "design_and_composition_duration_formatted": "2m 24s",
    "entertainment_duration_formatted": "38m 50s",
    "news_duration_formatted": "4m 32s",
    "software_development_duration_formatted": "5h 59m",
    "reference_and_learning_duration_formatted": "1h 13m",
    "shopping_duration_formatted": "1m 4s",
    "utilities_duration_formatted": "1h 54m"
  },
  {
    "id": 1648364400,
    "date": "2022-03-27",
    "productivity_pulse": 71,
    "very_productive_percentage": 38.9,
    "productive_percentage": 35.3,
    "neutral_percentage": 3.6,
    "distracting_percentage": 17.2,
    "very_distracting_percentage": 5.0,
    "all_productive_percentage": 74.2,
    "all_distracting_percentage": 22.3,
    "uncategorized_percentage": 0.6,
    "business_percentage": 4.9,
    "communication_and_scheduling_percentage": 20.3,
    "social_networking_percentage": 3.9,
    "design_and_composition_percentage": 1.7,
    "entertainment_percentage": 3.7,
    "news_percentage": 0.9,
    "software_development_percentage": 31.8,
    "reference_and_learning_percentage": 23.1,
    "shopping_percentage": 0.0,
    "utilities_percentage": 9.0,
    "total_hours": 7.13,
    "very_productive_hours": 2.78,
    "productive_hours": 2.51,
    "neutral_hours": 0.26,
    "distracting_hours": 1.23,
    "very_distracting_hours": 0.36,
    "all_productive_hours": 5.29,
    "all_distracting_hours": 1.59,
    "uncategorized_hours": 0.04,
    "business_hours": 0.35,
    "communication_and_scheduling_hours": 1.45,
    "social_networking_hours": 0.28,
    "design_and_composition_hours": 0.12,
    "entertainment_hours": 0.26,
    "news_hours": 0.06,
    "software_development_hours": 2.27,
    "reference_and_learning_hours": 1.65,
    "shopping_hours": 0.0,
    "utilities_hours": 0.64,
    "total_duration_formatted": "7h 7m",
    "very_productive_duration_formatted": "2h 46m",
    "productive_duration_formatted": "2h 30m",
    "neutral_duration_formatted": "15m 19s",
    "distracting_duration_formatted": "1h 13m",
    "very_distracting_duration_formatted": "21m 36s",
    "all_productive_duration_formatted": "5h 17m",
    "all_distracting_duration_formatted": "1h 35m",
    "uncategorized_duration_formatted": "2m 38s",
    "business_duration_formatted": "20m 48s",
    "communication_and_scheduling_duration_formatted": "1h 27m",
    "social_networking_duration_formatted": "16m 51s",
    "design_and_composition_duration_formatted": "7m 25s",
    "entertainment_duration_formatted": "15m 53s",
    "news_duration_formatted": "3m 53s",
    "software_development_duration_formatted": "2h 16m",
    "reference_and_learning_duration_formatted": "1h 38m",
    "shopping_duration_formatted": "no time",
    "utilities_duration_formatted": "38m 33s"
  },
  {
    "id": 1648278000,
    "date": "2022-03-26",
    "productivity_pulse": 59,
    "very_productive_percentage": 17.5,
    "productive_percentage": 40.1,
    "neutral_percentage": 5.7,
    "distracting_percentage": 36.3,
    "very_distracting_percentage": 0.4,
    "all_productive_percentage": 57.6,
    "all_distracting_percentage": 36.7,
    "uncategorized_percentage": 1.5,
    "business_percentage": 0.0,
    "communication_and_scheduling_percentage": 37.0,
    "social_networking_percentage": 3.0,
    "design_and_composition_percentage": 16.6,
    "entertainment_percentage": 2.9,
    "news_percentage": 0.0,
    "software_development_percentage": 0.0,
    "reference_and_learning_percentage": 9.2,
    "shopping_percentage": 0.4,
    "utilities_percentage": 29.4,
    "total_hours": 1.62,
    "very_productive_hours": 0.28,
    "productive_hours": 0.65,
    "neutral_hours": 0.09,
    "distracting_hours": 0.59,
    "very_distracting_hours": 0.01,
    "all_productive_hours": 0.93,
    "all_distracting_hours": 0.59,
    "uncategorized_hours": 0.02,
    "business_hours": 0.0,
    "communication_and_scheduling_hours": 0.6,
    "social_networking_hours": 0.05,
    "design_and_composition_hours": 0.27,
    "entertainment_hours": 0.05,
    "news_hours": 0.0,
    "software_development_hours": 0.0,
    "reference_and_learning_hours": 0.15,
    "shopping_hours": 0.01,
    "utilities_hours": 0.47,
    "total_duration_formatted": "1h 36m",
    "very_productive_duration_formatted": "16m 58s",
    "productive_duration_formatted": "38m 51s",
    "neutral_duration_formatted": "5m 34s",
    "distracting_duration_formatted": "35m 10s",
    "very_distracting_duration_formatted": "22s",
    "all_productive_duration_formatted": "55m 49s",
    "all_distracting_duration_formatted": "35m 32s",
    "uncategorized_duration_formatted": "1m 27s",
    "business_duration_formatted": "2s",
    "communication_and_scheduling_duration_formatted": "35m 51s",
    "social_networking_duration_formatted": "2m 56s",
    "design_and_composition_duration_formatted": "16m 3s",
    "entertainment_duration_formatted": "2m 49s",
    "news_duration_formatted": "no time",
    "software_development_duration_formatted": "no time",
    "reference_and_learning_duration_formatted": "8m 57s",
    "shopping_duration_formatted": "22s",
    "utilities_duration_formatted": "28m 28s"
  },
  {
    "id": 1648191600,
    "date": "2022-03-25",
    "productivity_pulse": 63,
    "very_productive_percentage": 23.4,
    "productive_percentage": 43.5,
    "neutral_percentage": 8.0,
    "distracting_percentage": 15.3,
    "very_distracting_percentage": 9.8,
    "all_productive_percentage": 67.0,
    "all_distracting_percentage": 25.0,
    "uncategorized_percentage": 1.6,
    "business_percentage": 6.3,
    "communication_and_scheduling_percentage": 16.5,
    "social_networking_percentage": 12.7,
    "design_and_composition_percentage": 16.8,
    "entertainment_percentage": 9.5,
    "news_percentage": 0.0,
    "software_development_percentage": 0.5,
    "reference_and_learning_percentage": 4.0,
    "shopping_percentage": 0.0,
    "utilities_percentage": 32.1,
    "total_hours": 7.15,
    "very_productive_hours": 1.68,
    "productive_hours": 3.11,
    "neutral_hours": 0.57,
    "distracting_hours": 1.09,
    "very_distracting_hours": 0.7,
    "all_productive_hours": 4.79,
    "all_distracting_hours": 1.79,
    "uncategorized_hours": 0.11,
    "business_hours": 0.45,
    "communication_and_scheduling_hours": 1.18,
    "social_networking_hours": 0.91,
    "design_and_composition_hours": 1.2,
    "entertainment_hours": 0.68,
    "news_hours": 0.0,
    "software_development_hours": 0.04,
    "reference_and_learning_hours": 0.28,
    "shopping_hours": 0.0,
    "utilities_hours": 2.3,
    "total_duration_formatted": "7h 9m",
    "very_productive_duration_formatted": "1h 40m",
    "productive_duration_formatted": "3h 6m",
    "neutral_duration_formatted": "34m 21s",
    "distracting_duration_formatted": "1h 5m",
    "very_distracting_duration_formatted": "41m 52s",
    "all_productive_duration_formatted": "4h 47m",
    "all_distracting_duration_formatted": "1h 47m",
    "uncategorized_duration_formatted": "6m 40s",
    "business_duration_formatted": "27m 15s",
    "communication_and_scheduling_duration_formatted": "1h 10m",
    "social_networking_duration_formatted": "54m 28s",
    "design_and_composition_duration_formatted": "1h 12m",
    "entertainment_duration_formatted": "40m 35s",
    "news_duration_formatted": "2s",
    "software_development_duration_formatted": "2m 21s",
    "reference_and_learning_duration_formatted": "17m",
    "shopping_duration_formatted": "2s",
    "utilities_duration_formatted": "2h 17m"
  },
  {
    "id": 1648105200,
    "date": "2022-03-24",
    "productivity_pulse": 80,
    "very_productive_percentage": 46.3,
    "productive_percentage": 41.5,
    "neutral_percentage": 3.7,
    "distracting_percentage": 5.2,
    "very_distracting_percentage": 3.3,
    "all_productive_percentage": 87.8,
    "all_distracting_percentage": 8.4,
    "uncategorized_percentage": 2.5,
    "business_percentage": 3.4,
    "communication_and_scheduling_percentage": 5.4,
    "social_networking_percentage": 4.4,
    "design_and_composition_percentage": 0.7,
    "entertainment_percentage": 3.1,
    "news_percentage": 0.4,
    "software_development_percentage": 42.3,
    "reference_and_learning_percentage": 5.1,
    "shopping_percentage": 0.0,
    "utilities_percentage": 32.8,
    "total_hours": 25.59,
    "very_productive_hours": 11.86,
    "productive_hours": 10.61,
    "neutral_hours": 0.96,
    "distracting_hours": 1.32,
    "very_distracting_hours": 0.84,
    "all_productive_hours": 22.47,
    "all_distracting_hours": 2.16,
    "uncategorized_hours": 0.63,
    "business_hours": 0.86,
    "communication_and_scheduling_hours": 1.38,
    "social_networking_hours": 1.11,
    "design_and_composition_hours": 0.19,
    "entertainment_hours": 0.8,
    "news_hours": 0.11,
    "software_development_hours": 10.82,
    "reference_and_learning_hours": 1.3,
    "shopping_hours": 0.0,
    "utilities_hours": 8.39,
    "total_duration_formatted": "25h 35m",
    "very_productive_duration_formatted": "11h 51m",
    "productive_duration_formatted": "10h 36m",
    "neutral_duration_formatted": "57m 33s",
    "distracting_duration_formatted": "1h 19m",
    "very_distracting_duration_formatted": "50m 13s",
    "all_productive_duration_formatted": "22h 28m",
    "all_distracting_duration_formatted": "2h 9m",
    "uncategorized_duration_formatted": "37m 37s",
    "business_duration_formatted": "51m 43s",
    "communication_and_scheduling_duration_formatted": "1h 22m",
    "social_networking_duration_formatted": "1h 6m",
    "design_and_composition_duration_formatted": "11m 30s",
    "entertainment_duration_formatted": "48m 8s",
    "news_duration_formatted": "6m 18s",
    "software_development_duration_formatted": "10h 48m",
    "reference_and_learning_duration_formatted": "1h 18m",
    "shopping_duration_formatted": "no time",
    "utilities_duration_formatted": "8h 23m"
  },
  {
    "id": 1648018800,
    "date": "2022-03-23",
    "productivity_pulse": 67,
    "very_productive_percentage": 28.8,
    "productive_percentage": 44.8,
    "neutral_percentage": 6.8,
    "distracting_percentage": 7.7,
    "very_distracting_percentage": 11.9,
    "all_productive_percentage": 73.6,
    "all_distracting_percentage": 19.6,
    "uncategorized_percentage": 1.5,
    "business_percentage": 4.9,
    "communication_and_scheduling_percentage": 10.4,
    "social_networking_percentage": 5.1,
    "design_and_composition_percentage": 3.5,
    "entertainment_percentage": 13.8,
    "news_percentage": 0.0,
    "software_development_percentage": 20.5,
    "reference_and_learning_percentage": 5.5,
    "shopping_percentage": 0.4,
    "utilities_percentage": 34.3,
    "total_hours": 14.35,
    "very_productive_hours": 4.14,
    "productive_hours": 6.42,
    "neutral_hours": 0.97,
    "distracting_hours": 1.11,
    "very_distracting_hours": 1.71,
    "all_productive_hours": 10.56,
    "all_distracting_hours": 2.82,
    "uncategorized_hours": 0.22,
    "business_hours": 0.71,
    "communication_and_scheduling_hours": 1.5,
    "social_networking_hours": 0.73,
    "design_and_composition_hours": 0.5,
    "entertainment_hours": 1.98,
    "news_hours": 0.0,
    "software_development_hours": 2.95,
    "reference_and_learning_hours": 0.79,
    "shopping_hours": 0.06,
    "utilities_hours": 4.92,
    "total_duration_formatted": "14h 21m",
    "very_productive_duration_formatted": "4h 8m",
    "productive_duration_formatted": "6h 25m",
    "neutral_duration_formatted": "58m 9s",
    "distracting_duration_formatted": "1h 6m",
    "very_distracting_duration_formatted": "1h 42m",
    "all_productive_duration_formatted": "10h 33m",
    "all_distracting_duration_formatted": "2h 49m",
    "uncategorized_duration_formatted": "13m 8s",
    "business_duration_formatted": "42m 19s",
    "communication_and_scheduling_duration_formatted": "1h 29m",
    "social_networking_duration_formatted": "43m 39s",
    "design_and_composition_duration_formatted": "29m 59s",
    "entertainment_duration_formatted": "1h 58m",
    "news_duration_formatted": "5s",
    "software_development_duration_formatted": "2h 56m",
    "reference_and_learning_duration_formatted": "47m 33s",
    "shopping_duration_formatted": "3m 34s",
    "utilities_duration_formatted": "4h 55m"
  }
]
export default DataWeek;