const DataWeek=[
    {
      "id": 1648537200,
      "date": "2022-03-29",
      "productivity_pulse": 81,
      "very_productive_percentage": 52.9,
      "productive_percentage": 32.5,
      "neutral_percentage": 2.4,
      "distracting_percentage": 10.5,
      "very_distracting_percentage": 1.7,
      "all_productive_percentage": 85.4,
      "all_distracting_percentage": 12.1,
      "uncategorized_percentage": 0.3,
      "business_percentage": 1.2,
      "communication_and_scheduling_percentage": 7.5,
      "social_networking_percentage": 4.9,
      "design_and_composition_percentage": 5.4,
      "entertainment_percentage": 4.3,
      "news_percentage": 0.5,
      "software_development_percentage": 46.3,
      "reference_and_learning_percentage": 4.8,
      "shopping_percentage": 0.0,
      "utilities_percentage": 24.7,
      "total_hours": 21.1,
      "very_productive_hours": 11.17,
      "productive_hours": 6.86,
      "neutral_hours": 0.52,
      "distracting_hours": 2.21,
      "very_distracting_hours": 0.35,
      "all_productive_hours": 18.03,
      "all_distracting_hours": 2.56,
      "uncategorized_hours": 0.07,
      "business_hours": 0.26,
      "communication_and_scheduling_hours": 1.59,
      "social_networking_hours": 1.04,
      "design_and_composition_hours": 1.13,
      "entertainment_hours": 0.91,
      "news_hours": 0.1,
      "software_development_hours": 9.78,
      "reference_and_learning_hours": 1.01,
      "shopping_hours": 0.01,
      "utilities_hours": 5.22,
      "total_duration_formatted": "21h 6m",
      "very_productive_duration_formatted": "11h 9m",
      "productive_duration_formatted": "6h 51m",
      "neutral_duration_formatted": "30m 59s",
      "distracting_duration_formatted": "2h 12m",
      "very_distracting_duration_formatted": "21m 5s",
      "all_productive_duration_formatted": "18h 1m",
      "all_distracting_duration_formatted": "2h 33m",
      "uncategorized_duration_formatted": "4m 1s",
      "business_duration_formatted": "15m 31s",
      "communication_and_scheduling_duration_formatted": "1h 35m",
      "social_networking_duration_formatted": "1h 2m",
      "design_and_composition_duration_formatted": "1h 7m",
      "entertainment_duration_formatted": "54m 27s",
      "news_duration_formatted": "5m 44s",
      "software_development_duration_formatted": "9h 46m",
      "reference_and_learning_duration_formatted": "1h",
      "shopping_duration_formatted": "30s",
      "utilities_duration_formatted": "5h 13m"
    },
    {
      "id": 1648450800,
      "date": "2022-03-28",
      "productivity_pulse": 70,
      "very_productive_percentage": 35.5,
      "productive_percentage": 39.8,
      "neutral_percentage": 3.3,
      "distracting_percentage": 15.2,
      "very_distracting_percentage": 6.2,
      "all_productive_percentage": 75.3,
      "all_distracting_percentage": 21.4,
      "uncategorized_percentage": 0.4,
      "business_percentage": 1.6,
      "communication_and_scheduling_percentage": 14.2,
      "social_networking_percentage": 9.8,
      "design_and_composition_percentage": 0.3,
      "entertainment_percentage": 4.8,
      "news_percentage": 0.6,
      "software_development_percentage": 33.7,
      "reference_and_learning_percentage": 4.2,
      "shopping_percentage": 0.1,
      "utilities_percentage": 30.2,
      "total_hours": 13.38,
      "very_productive_hours": 4.75,
      "productive_hours": 5.33,
      "neutral_hours": 0.44,
      "distracting_hours": 2.03,
      "very_distracting_hours": 0.83,
      "all_productive_hours": 10.08,
      "all_distracting_hours": 2.86,
      "uncategorized_hours": 0.05,
      "business_hours": 0.22,
      "communication_and_scheduling_hours": 1.9,
      "social_networking_hours": 1.31,
      "design_and_composition_hours": 0.04,
      "entertainment_hours": 0.65,
      "news_hours": 0.08,
      "software_development_hours": 4.51,
      "reference_and_learning_hours": 0.57,
      "shopping_hours": 0.02,
      "utilities_hours": 4.04,
      "total_duration_formatted": "13h 23m",
      "very_productive_duration_formatted": "4h 45m",
      "productive_duration_formatted": "5h 19m",
      "neutral_duration_formatted": "26m 28s",
      "distracting_duration_formatted": "2h 1m",
      "very_distracting_duration_formatted": "49m 47s",
      "all_productive_duration_formatted": "10h 4m",
      "all_distracting_duration_formatted": "2h 51m",
      "uncategorized_duration_formatted": "2m 58s",
      "business_duration_formatted": "13m 4s",
      "communication_and_scheduling_duration_formatted": "1h 54m",
      "social_networking_duration_formatted": "1h 18m",
      "design_and_composition_duration_formatted": "2m 24s",
      "entertainment_duration_formatted": "38m 50s",
      "news_duration_formatted": "4m 32s",
      "software_development_duration_formatted": "4h 30m",
      "reference_and_learning_duration_formatted": "33m 58s",
      "shopping_duration_formatted": "1m 4s",
      "utilities_duration_formatted": "4h 2m"
    },
    {
      "id": 1648364400,
      "date": "2022-03-27",
      "productivity_pulse": 69,
      "very_productive_percentage": 33.9,
      "productive_percentage": 37.6,
      "neutral_percentage": 6.2,
      "distracting_percentage": 17.2,
      "very_distracting_percentage": 5.0,
      "all_productive_percentage": 71.6,
      "all_distracting_percentage": 22.3,
      "uncategorized_percentage": 3.2,
      "business_percentage": 4.9,
      "communication_and_scheduling_percentage": 20.3,
      "social_networking_percentage": 3.9,
      "design_and_composition_percentage": 1.7,
      "entertainment_percentage": 3.7,
      "news_percentage": 0.9,
      "software_development_percentage": 26.8,
      "reference_and_learning_percentage": 9.6,
      "shopping_percentage": 0.0,
      "utilities_percentage": 24.9,
      "total_hours": 7.13,
      "very_productive_hours": 2.42,
      "productive_hours": 2.68,
      "neutral_hours": 0.44,
      "distracting_hours": 1.23,
      "very_distracting_hours": 0.36,
      "all_productive_hours": 5.11,
      "all_distracting_hours": 1.59,
      "uncategorized_hours": 0.23,
      "business_hours": 0.35,
      "communication_and_scheduling_hours": 1.45,
      "social_networking_hours": 0.28,
      "design_and_composition_hours": 0.12,
      "entertainment_hours": 0.26,
      "news_hours": 0.06,
      "software_development_hours": 1.91,
      "reference_and_learning_hours": 0.69,
      "shopping_hours": 0.0,
      "utilities_hours": 1.77,
      "total_duration_formatted": "7h 7m",
      "very_productive_duration_formatted": "2h 25m",
      "productive_duration_formatted": "2h 41m",
      "neutral_duration_formatted": "26m 24s",
      "distracting_duration_formatted": "1h 13m",
      "very_distracting_duration_formatted": "21m 36s",
      "all_productive_duration_formatted": "5h 6m",
      "all_distracting_duration_formatted": "1h 35m",
      "uncategorized_duration_formatted": "13m 43s",
      "business_duration_formatted": "20m 48s",
      "communication_and_scheduling_duration_formatted": "1h 27m",
      "social_networking_duration_formatted": "16m 51s",
      "design_and_composition_duration_formatted": "7m 25s",
      "entertainment_duration_formatted": "15m 53s",
      "news_duration_formatted": "3m 53s",
      "software_development_duration_formatted": "1h 54m",
      "reference_and_learning_duration_formatted": "41m 13s",
      "shopping_duration_formatted": "no time",
      "utilities_duration_formatted": "1h 46m"
    },
    {
      "id": 1648278000,
      "date": "2022-03-26",
      "productivity_pulse": 59,
      "very_productive_percentage": 17.5,
      "productive_percentage": 40.1,
      "neutral_percentage": 5.7,
      "distracting_percentage": 36.3,
      "very_distracting_percentage": 0.4,
      "all_productive_percentage": 57.6,
      "all_distracting_percentage": 36.7,
      "uncategorized_percentage": 1.5,
      "business_percentage": 0.0,
      "communication_and_scheduling_percentage": 37.0,
      "social_networking_percentage": 3.0,
      "design_and_composition_percentage": 16.6,
      "entertainment_percentage": 2.9,
      "news_percentage": 0.0,
      "software_development_percentage": 0.0,
      "reference_and_learning_percentage": 9.2,
      "shopping_percentage": 0.4,
      "utilities_percentage": 29.4,
      "total_hours": 1.62,
      "very_productive_hours": 0.28,
      "productive_hours": 0.65,
      "neutral_hours": 0.09,
      "distracting_hours": 0.59,
      "very_distracting_hours": 0.01,
      "all_productive_hours": 0.93,
      "all_distracting_hours": 0.59,
      "uncategorized_hours": 0.02,
      "business_hours": 0.0,
      "communication_and_scheduling_hours": 0.6,
      "social_networking_hours": 0.05,
      "design_and_composition_hours": 0.27,
      "entertainment_hours": 0.05,
      "news_hours": 0.0,
      "software_development_hours": 0.0,
      "reference_and_learning_hours": 0.15,
      "shopping_hours": 0.01,
      "utilities_hours": 0.47,
      "total_duration_formatted": "1h 36m",
      "very_productive_duration_formatted": "16m 58s",
      "productive_duration_formatted": "38m 51s",
      "neutral_duration_formatted": "5m 34s",
      "distracting_duration_formatted": "35m 10s",
      "very_distracting_duration_formatted": "22s",
      "all_productive_duration_formatted": "55m 49s",
      "all_distracting_duration_formatted": "35m 32s",
      "uncategorized_duration_formatted": "1m 27s",
      "business_duration_formatted": "2s",
      "communication_and_scheduling_duration_formatted": "35m 51s",
      "social_networking_duration_formatted": "2m 56s",
      "design_and_composition_duration_formatted": "16m 3s",
      "entertainment_duration_formatted": "2m 49s",
      "news_duration_formatted": "no time",
      "software_development_duration_formatted": "no time",
      "reference_and_learning_duration_formatted": "8m 57s",
      "shopping_duration_formatted": "22s",
      "utilities_duration_formatted": "28m 28s"
    },
    {
      "id": 1648191600,
      "date": "2022-03-25",
      "productivity_pulse": 63,
      "very_productive_percentage": 23.4,
      "productive_percentage": 43.5,
      "neutral_percentage": 8.0,
      "distracting_percentage": 15.3,
      "very_distracting_percentage": 9.8,
      "all_productive_percentage": 67.0,
      "all_distracting_percentage": 25.0,
      "uncategorized_percentage": 1.6,
      "business_percentage": 6.3,
      "communication_and_scheduling_percentage": 16.5,
      "social_networking_percentage": 12.7,
      "design_and_composition_percentage": 16.8,
      "entertainment_percentage": 9.5,
      "news_percentage": 0.0,
      "software_development_percentage": 0.5,
      "reference_and_learning_percentage": 4.0,
      "shopping_percentage": 0.0,
      "utilities_percentage": 32.1,
      "total_hours": 7.15,
      "very_productive_hours": 1.68,
      "productive_hours": 3.11,
      "neutral_hours": 0.57,
      "distracting_hours": 1.09,
      "very_distracting_hours": 0.7,
      "all_productive_hours": 4.79,
      "all_distracting_hours": 1.79,
      "uncategorized_hours": 0.11,
      "business_hours": 0.45,
      "communication_and_scheduling_hours": 1.18,
      "social_networking_hours": 0.91,
      "design_and_composition_hours": 1.2,
      "entertainment_hours": 0.68,
      "news_hours": 0.0,
      "software_development_hours": 0.04,
      "reference_and_learning_hours": 0.28,
      "shopping_hours": 0.0,
      "utilities_hours": 2.3,
      "total_duration_formatted": "7h 9m",
      "very_productive_duration_formatted": "1h 40m",
      "productive_duration_formatted": "3h 6m",
      "neutral_duration_formatted": "34m 21s",
      "distracting_duration_formatted": "1h 5m",
      "very_distracting_duration_formatted": "41m 52s",
      "all_productive_duration_formatted": "4h 47m",
      "all_distracting_duration_formatted": "1h 47m",
      "uncategorized_duration_formatted": "6m 40s",
      "business_duration_formatted": "27m 15s",
      "communication_and_scheduling_duration_formatted": "1h 10m",
      "social_networking_duration_formatted": "54m 28s",
      "design_and_composition_duration_formatted": "1h 12m",
      "entertainment_duration_formatted": "40m 35s",
      "news_duration_formatted": "2s",
      "software_development_duration_formatted": "2m 21s",
      "reference_and_learning_duration_formatted": "17m",
      "shopping_duration_formatted": "2s",
      "utilities_duration_formatted": "2h 17m"
    },
    {
      "id": 1648105200,
      "date": "2022-03-24",
      "productivity_pulse": 80,
      "very_productive_percentage": 46.3,
      "productive_percentage": 41.5,
      "neutral_percentage": 3.7,
      "distracting_percentage": 5.2,
      "very_distracting_percentage": 3.3,
      "all_productive_percentage": 87.8,
      "all_distracting_percentage": 8.4,
      "uncategorized_percentage": 2.5,
      "business_percentage": 3.4,
      "communication_and_scheduling_percentage": 5.4,
      "social_networking_percentage": 4.4,
      "design_and_composition_percentage": 0.7,
      "entertainment_percentage": 3.1,
      "news_percentage": 0.4,
      "software_development_percentage": 42.3,
      "reference_and_learning_percentage": 5.1,
      "shopping_percentage": 0.0,
      "utilities_percentage": 32.8,
      "total_hours": 25.59,
      "very_productive_hours": 11.86,
      "productive_hours": 10.61,
      "neutral_hours": 0.96,
      "distracting_hours": 1.32,
      "very_distracting_hours": 0.84,
      "all_productive_hours": 22.47,
      "all_distracting_hours": 2.16,
      "uncategorized_hours": 0.63,
      "business_hours": 0.86,
      "communication_and_scheduling_hours": 1.38,
      "social_networking_hours": 1.11,
      "design_and_composition_hours": 0.19,
      "entertainment_hours": 0.8,
      "news_hours": 0.11,
      "software_development_hours": 10.82,
      "reference_and_learning_hours": 1.3,
      "shopping_hours": 0.0,
      "utilities_hours": 8.39,
      "total_duration_formatted": "25h 35m",
      "very_productive_duration_formatted": "11h 51m",
      "productive_duration_formatted": "10h 36m",
      "neutral_duration_formatted": "57m 33s",
      "distracting_duration_formatted": "1h 19m",
      "very_distracting_duration_formatted": "50m 13s",
      "all_productive_duration_formatted": "22h 28m",
      "all_distracting_duration_formatted": "2h 9m",
      "uncategorized_duration_formatted": "37m 37s",
      "business_duration_formatted": "51m 43s",
      "communication_and_scheduling_duration_formatted": "1h 22m",
      "social_networking_duration_formatted": "1h 6m",
      "design_and_composition_duration_formatted": "11m 30s",
      "entertainment_duration_formatted": "48m 8s",
      "news_duration_formatted": "6m 18s",
      "software_development_duration_formatted": "10h 48m",
      "reference_and_learning_duration_formatted": "1h 18m",
      "shopping_duration_formatted": "no time",
      "utilities_duration_formatted": "8h 23m"
    },
    {
      "id": 1648018800,
      "date": "2022-03-23",
      "productivity_pulse": 67,
      "very_productive_percentage": 28.8,
      "productive_percentage": 44.8,
      "neutral_percentage": 6.8,
      "distracting_percentage": 7.7,
      "very_distracting_percentage": 11.9,
      "all_productive_percentage": 73.6,
      "all_distracting_percentage": 19.6,
      "uncategorized_percentage": 1.5,
      "business_percentage": 4.9,
      "communication_and_scheduling_percentage": 10.4,
      "social_networking_percentage": 5.1,
      "design_and_composition_percentage": 3.5,
      "entertainment_percentage": 13.8,
      "news_percentage": 0.0,
      "software_development_percentage": 20.5,
      "reference_and_learning_percentage": 5.5,
      "shopping_percentage": 0.4,
      "utilities_percentage": 34.3,
      "total_hours": 14.35,
      "very_productive_hours": 4.14,
      "productive_hours": 6.42,
      "neutral_hours": 0.97,
      "distracting_hours": 1.11,
      "very_distracting_hours": 1.71,
      "all_productive_hours": 10.56,
      "all_distracting_hours": 2.82,
      "uncategorized_hours": 0.22,
      "business_hours": 0.71,
      "communication_and_scheduling_hours": 1.5,
      "social_networking_hours": 0.73,
      "design_and_composition_hours": 0.5,
      "entertainment_hours": 1.98,
      "news_hours": 0.0,
      "software_development_hours": 2.95,
      "reference_and_learning_hours": 0.79,
      "shopping_hours": 0.06,
      "utilities_hours": 4.92,
      "total_duration_formatted": "14h 21m",
      "very_productive_duration_formatted": "4h 8m",
      "productive_duration_formatted": "6h 25m",
      "neutral_duration_formatted": "58m 9s",
      "distracting_duration_formatted": "1h 6m",
      "very_distracting_duration_formatted": "1h 42m",
      "all_productive_duration_formatted": "10h 33m",
      "all_distracting_duration_formatted": "2h 49m",
      "uncategorized_duration_formatted": "13m 8s",
      "business_duration_formatted": "42m 19s",
      "communication_and_scheduling_duration_formatted": "1h 29m",
      "social_networking_duration_formatted": "43m 39s",
      "design_and_composition_duration_formatted": "29m 59s",
      "entertainment_duration_formatted": "1h 58m",
      "news_duration_formatted": "5s",
      "software_development_duration_formatted": "2h 56m",
      "reference_and_learning_duration_formatted": "47m 33s",
      "shopping_duration_formatted": "3m 34s",
      "utilities_duration_formatted": "4h 55m"
    },
    {
      "id": 1647932400,
      "date": "2022-03-22",
      "productivity_pulse": 66,
      "very_productive_percentage": 30.4,
      "productive_percentage": 44.7,
      "neutral_percentage": 3.5,
      "distracting_percentage": 2.7,
      "very_distracting_percentage": 18.7,
      "all_productive_percentage": 75.1,
      "all_distracting_percentage": 21.5,
      "uncategorized_percentage": 1.4,
      "business_percentage": 6.1,
      "communication_and_scheduling_percentage": 4.6,
      "social_networking_percentage": 3.6,
      "design_and_composition_percentage": 0.3,
      "entertainment_percentage": 16.3,
      "news_percentage": 1.6,
      "software_development_percentage": 23.1,
      "reference_and_learning_percentage": 10.1,
      "shopping_percentage": 0.3,
      "utilities_percentage": 32.6,
      "total_hours": 23.82,
      "very_productive_hours": 7.24,
      "productive_hours": 10.64,
      "neutral_hours": 0.83,
      "distracting_hours": 0.65,
      "very_distracting_hours": 4.47,
      "all_productive_hours": 17.88,
      "all_distracting_hours": 5.12,
      "uncategorized_hours": 0.33,
      "business_hours": 1.45,
      "communication_and_scheduling_hours": 1.09,
      "social_networking_hours": 0.86,
      "design_and_composition_hours": 0.08,
      "entertainment_hours": 3.88,
      "news_hours": 0.38,
      "software_development_hours": 5.51,
      "reference_and_learning_hours": 2.42,
      "shopping_hours": 0.06,
      "utilities_hours": 7.77,
      "total_duration_formatted": "23h 49m",
      "very_productive_duration_formatted": "7h 14m",
      "productive_duration_formatted": "10h 38m",
      "neutral_duration_formatted": "49m 39s",
      "distracting_duration_formatted": "38m 59s",
      "very_distracting_duration_formatted": "4h 27m",
      "all_productive_duration_formatted": "17h 52m",
      "all_distracting_duration_formatted": "5h 6m",
      "uncategorized_duration_formatted": "19m 49s",
      "business_duration_formatted": "1h 26m",
      "communication_and_scheduling_duration_formatted": "1h 5m",
      "social_networking_duration_formatted": "51m 36s",
      "design_and_composition_duration_formatted": "4m 46s",
      "entertainment_duration_formatted": "3h 52m",
      "news_duration_formatted": "22m 35s",
      "software_development_duration_formatted": "5h 30m",
      "reference_and_learning_duration_formatted": "2h 24m",
      "shopping_duration_formatted": "3m 39s",
      "utilities_duration_formatted": "7h 46m"
    },
    {
      "id": 1647846000,
      "date": "2022-03-21",
      "productivity_pulse": 73,
      "very_productive_percentage": 44.0,
      "productive_percentage": 31.1,
      "neutral_percentage": 5.5,
      "distracting_percentage": 15.0,
      "very_distracting_percentage": 4.3,
      "all_productive_percentage": 75.2,
      "all_distracting_percentage": 19.3,
      "uncategorized_percentage": 3.4,
      "business_percentage": 6.7,
      "communication_and_scheduling_percentage": 16.4,
      "social_networking_percentage": 3.2,
      "design_and_composition_percentage": 9.5,
      "entertainment_percentage": 1.0,
      "news_percentage": 2.3,
      "software_development_percentage": 27.8,
      "reference_and_learning_percentage": 8.3,
      "shopping_percentage": 0.0,
      "utilities_percentage": 21.4,
      "total_hours": 16.2,
      "very_productive_hours": 7.13,
      "productive_hours": 5.05,
      "neutral_hours": 0.89,
      "distracting_hours": 2.44,
      "very_distracting_hours": 0.7,
      "all_productive_hours": 12.18,
      "all_distracting_hours": 3.13,
      "uncategorized_hours": 0.55,
      "business_hours": 1.09,
      "communication_and_scheduling_hours": 2.65,
      "social_networking_hours": 0.51,
      "design_and_composition_hours": 1.55,
      "entertainment_hours": 0.17,
      "news_hours": 0.37,
      "software_development_hours": 4.5,
      "reference_and_learning_hours": 1.34,
      "shopping_hours": 0.0,
      "utilities_hours": 3.46,
      "total_duration_formatted": "16h 11m",
      "very_productive_duration_formatted": "7h 8m",
      "productive_duration_formatted": "5h 2m",
      "neutral_duration_formatted": "53m 18s",
      "distracting_duration_formatted": "2h 26m",
      "very_distracting_duration_formatted": "41m 49s",
      "all_productive_duration_formatted": "12h 10m",
      "all_distracting_duration_formatted": "3h 7m",
      "uncategorized_duration_formatted": "33m 1s",
      "business_duration_formatted": "1h 5m",
      "communication_and_scheduling_duration_formatted": "2h 39m",
      "social_networking_duration_formatted": "30m 48s",
      "design_and_composition_duration_formatted": "1h 32m",
      "entertainment_duration_formatted": "10m 3s",
      "news_duration_formatted": "22m 27s",
      "software_development_duration_formatted": "4h 30m",
      "reference_and_learning_duration_formatted": "1h 20m",
      "shopping_duration_formatted": "no time",
      "utilities_duration_formatted": "3h 27m"
    },
    {
      "id": 1647759600,
      "date": "2022-03-20",
      "productivity_pulse": 47,
      "very_productive_percentage": 8.1,
      "productive_percentage": 34.9,
      "neutral_percentage": 6.8,
      "distracting_percentage": 39.6,
      "very_distracting_percentage": 10.6,
      "all_productive_percentage": 43.0,
      "all_distracting_percentage": 50.2,
      "uncategorized_percentage": 1.7,
      "business_percentage": 0.1,
      "communication_and_scheduling_percentage": 29.5,
      "social_networking_percentage": 3.5,
      "design_and_composition_percentage": 6.9,
      "entertainment_percentage": 22.4,
      "news_percentage": 0.0,
      "software_development_percentage": 0.7,
      "reference_and_learning_percentage": 24.1,
      "shopping_percentage": 0.1,
      "utilities_percentage": 11.0,
      "total_hours": 4.2,
      "very_productive_hours": 0.34,
      "productive_hours": 1.47,
      "neutral_hours": 0.29,
      "distracting_hours": 1.67,
      "very_distracting_hours": 0.44,
      "all_productive_hours": 1.81,
      "all_distracting_hours": 2.11,
      "uncategorized_hours": 0.07,
      "business_hours": 0.0,
      "communication_and_scheduling_hours": 1.24,
      "social_networking_hours": 0.15,
      "design_and_composition_hours": 0.29,
      "entertainment_hours": 0.94,
      "news_hours": 0.0,
      "software_development_hours": 0.03,
      "reference_and_learning_hours": 1.01,
      "shopping_hours": 0.01,
      "utilities_hours": 0.46,
      "total_duration_formatted": "4h 12m",
      "very_productive_duration_formatted": "20m 21s",
      "productive_duration_formatted": "1h 28m",
      "neutral_duration_formatted": "17m 11s",
      "distracting_duration_formatted": "1h 39m",
      "very_distracting_duration_formatted": "26m 40s",
      "all_productive_duration_formatted": "1h 48m",
      "all_distracting_duration_formatted": "2h 6m",
      "uncategorized_duration_formatted": "4m 18s",
      "business_duration_formatted": "17s",
      "communication_and_scheduling_duration_formatted": "1h 14m",
      "social_networking_duration_formatted": "8m 43s",
      "design_and_composition_duration_formatted": "17m 31s",
      "entertainment_duration_formatted": "56m 26s",
      "news_duration_formatted": "no time",
      "software_development_duration_formatted": "1m 48s",
      "reference_and_learning_duration_formatted": "1h",
      "shopping_duration_formatted": "19s",
      "utilities_duration_formatted": "27m 38s"
    },
    {
      "id": 1647673200,
      "date": "2022-03-19",
      "productivity_pulse": 53,
      "very_productive_percentage": 9.8,
      "productive_percentage": 44.8,
      "neutral_percentage": 3.0,
      "distracting_percentage": 34.3,
      "very_distracting_percentage": 8.0,
      "all_productive_percentage": 54.7,
      "all_distracting_percentage": 42.3,
      "uncategorized_percentage": 0.4,
      "business_percentage": 2.3,
      "communication_and_scheduling_percentage": 34.6,
      "social_networking_percentage": 6.6,
      "design_and_composition_percentage": 5.6,
      "entertainment_percentage": 1.5,
      "news_percentage": 2.1,
      "software_development_percentage": 1.6,
      "reference_and_learning_percentage": 33.0,
      "shopping_percentage": 0.0,
      "utilities_percentage": 12.3,
      "total_hours": 5.5,
      "very_productive_hours": 0.54,
      "productive_hours": 2.46,
      "neutral_hours": 0.17,
      "distracting_hours": 1.89,
      "very_distracting_hours": 0.44,
      "all_productive_hours": 3.01,
      "all_distracting_hours": 2.33,
      "uncategorized_hours": 0.02,
      "business_hours": 0.12,
      "communication_and_scheduling_hours": 1.9,
      "social_networking_hours": 0.36,
      "design_and_composition_hours": 0.31,
      "entertainment_hours": 0.08,
      "news_hours": 0.12,
      "software_development_hours": 0.09,
      "reference_and_learning_hours": 1.81,
      "shopping_hours": 0.0,
      "utilities_hours": 0.67,
      "total_duration_formatted": "5h 30m",
      "very_productive_duration_formatted": "32m 30s",
      "productive_duration_formatted": "2h 27m",
      "neutral_duration_formatted": "9m 58s",
      "distracting_duration_formatted": "1h 53m",
      "very_distracting_duration_formatted": "26m 34s",
      "all_productive_duration_formatted": "3h",
      "all_distracting_duration_formatted": "2h 19m",
      "uncategorized_duration_formatted": "1m 28s",
      "business_duration_formatted": "7m 29s",
      "communication_and_scheduling_duration_formatted": "1h 54m",
      "social_networking_duration_formatted": "21m 53s",
      "design_and_composition_duration_formatted": "18m 30s",
      "entertainment_duration_formatted": "5m 4s",
      "news_duration_formatted": "6m 55s",
      "software_development_duration_formatted": "5m 18s",
      "reference_and_learning_duration_formatted": "1h 48m",
      "shopping_duration_formatted": "no time",
      "utilities_duration_formatted": "40m 29s"
    },
    {
      "id": 1647586800,
      "date": "2022-03-18",
      "productivity_pulse": 70,
      "very_productive_percentage": 35.5,
      "productive_percentage": 39.3,
      "neutral_percentage": 4.6,
      "distracting_percentage": 13.0,
      "very_distracting_percentage": 7.6,
      "all_productive_percentage": 74.8,
      "all_distracting_percentage": 20.6,
      "uncategorized_percentage": 1.1,
      "business_percentage": 17.6,
      "communication_and_scheduling_percentage": 12.2,
      "social_networking_percentage": 8.7,
      "design_and_composition_percentage": 2.9,
      "entertainment_percentage": 7.9,
      "news_percentage": 0.4,
      "software_development_percentage": 14.5,
      "reference_and_learning_percentage": 11.0,
      "shopping_percentage": 0.0,
      "utilities_percentage": 23.8,
      "total_hours": 13.49,
      "very_productive_hours": 4.79,
      "productive_hours": 5.3,
      "neutral_hours": 0.61,
      "distracting_hours": 1.75,
      "very_distracting_hours": 1.03,
      "all_productive_hours": 10.09,
      "all_distracting_hours": 2.78,
      "uncategorized_hours": 0.15,
      "business_hours": 2.38,
      "communication_and_scheduling_hours": 1.64,
      "social_networking_hours": 1.17,
      "design_and_composition_hours": 0.39,
      "entertainment_hours": 1.06,
      "news_hours": 0.06,
      "software_development_hours": 1.95,
      "reference_and_learning_hours": 1.48,
      "shopping_hours": 0.01,
      "utilities_hours": 3.22,
      "total_duration_formatted": "13h 29m",
      "very_productive_duration_formatted": "4h 47m",
      "productive_duration_formatted": "5h 18m",
      "neutral_duration_formatted": "36m 51s",
      "distracting_duration_formatted": "1h 45m",
      "very_distracting_duration_formatted": "1h 1m",
      "all_productive_duration_formatted": "10h 5m",
      "all_distracting_duration_formatted": "2h 47m",
      "uncategorized_duration_formatted": "8m 46s",
      "business_duration_formatted": "2h 22m",
      "communication_and_scheduling_duration_formatted": "1h 38m",
      "social_networking_duration_formatted": "1h 10m",
      "design_and_composition_duration_formatted": "23m 7s",
      "entertainment_duration_formatted": "1h 3m",
      "news_duration_formatted": "3m 19s",
      "software_development_duration_formatted": "1h 57m",
      "reference_and_learning_duration_formatted": "1h 28m",
      "shopping_duration_formatted": "21s",
      "utilities_duration_formatted": "3h 13m"
    },
    {
      "id": 1647500400,
      "date": "2022-03-17",
      "productivity_pulse": 57,
      "very_productive_percentage": 24.2,
      "productive_percentage": 35.2,
      "neutral_percentage": 3.6,
      "distracting_percentage": 18.6,
      "very_distracting_percentage": 18.3,
      "all_productive_percentage": 59.4,
      "all_distracting_percentage": 36.9,
      "uncategorized_percentage": 1.9,
      "business_percentage": 2.5,
      "communication_and_scheduling_percentage": 18.6,
      "social_networking_percentage": 10.7,
      "design_and_composition_percentage": 1.4,
      "entertainment_percentage": 13.1,
      "news_percentage": 1.0,
      "software_development_percentage": 19.8,
      "reference_and_learning_percentage": 5.5,
      "shopping_percentage": 0.5,
      "utilities_percentage": 24.9,
      "total_hours": 10.79,
      "very_productive_hours": 2.61,
      "productive_hours": 3.8,
      "neutral_hours": 0.39,
      "distracting_hours": 2.01,
      "very_distracting_hours": 1.98,
      "all_productive_hours": 6.41,
      "all_distracting_hours": 3.98,
      "uncategorized_hours": 0.21,
      "business_hours": 0.27,
      "communication_and_scheduling_hours": 2.01,
      "social_networking_hours": 1.16,
      "design_and_composition_hours": 0.15,
      "entertainment_hours": 1.42,
      "news_hours": 0.11,
      "software_development_hours": 2.14,
      "reference_and_learning_hours": 0.59,
      "shopping_hours": 0.05,
      "utilities_hours": 2.69,
      "total_duration_formatted": "10h 47m",
      "very_productive_duration_formatted": "2h 36m",
      "productive_duration_formatted": "3h 47m",
      "neutral_duration_formatted": "23m 32s",
      "distracting_duration_formatted": "2h",
      "very_distracting_duration_formatted": "1h 58m",
      "all_productive_duration_formatted": "6h 24m",
      "all_distracting_duration_formatted": "3h 58m",
      "uncategorized_duration_formatted": "12m 20s",
      "business_duration_formatted": "16m 26s",
      "communication_and_scheduling_duration_formatted": "2h",
      "social_networking_duration_formatted": "1h 9m",
      "design_and_composition_duration_formatted": "9m 3s",
      "entertainment_duration_formatted": "1h 25m",
      "news_duration_formatted": "6m 23s",
      "software_development_duration_formatted": "2h 8m",
      "reference_and_learning_duration_formatted": "35m 17s",
      "shopping_duration_formatted": "3m 4s",
      "utilities_duration_formatted": "2h 41m"
    },
    {
      "id": 1647414000,
      "date": "2022-03-16",
      "productivity_pulse": 60,
      "very_productive_percentage": 16.3,
      "productive_percentage": 49.9,
      "neutral_percentage": 6.6,
      "distracting_percentage": 12.1,
      "very_distracting_percentage": 15.1,
      "all_productive_percentage": 66.2,
      "all_distracting_percentage": 27.2,
      "uncategorized_percentage": 3.7,
      "business_percentage": 5.2,
      "communication_and_scheduling_percentage": 12.2,
      "social_networking_percentage": 8.7,
      "design_and_composition_percentage": 1.7,
      "entertainment_percentage": 11.8,
      "news_percentage": 1.4,
      "software_development_percentage": 3.0,
      "reference_and_learning_percentage": 17.5,
      "shopping_percentage": 0.2,
      "utilities_percentage": 34.6,
      "total_hours": 14.45,
      "very_productive_hours": 2.35,
      "productive_hours": 7.21,
      "neutral_hours": 0.96,
      "distracting_hours": 1.74,
      "very_distracting_hours": 2.18,
      "all_productive_hours": 9.57,
      "all_distracting_hours": 3.93,
      "uncategorized_hours": 0.54,
      "business_hours": 0.75,
      "communication_and_scheduling_hours": 1.76,
      "social_networking_hours": 1.25,
      "design_and_composition_hours": 0.25,
      "entertainment_hours": 1.7,
      "news_hours": 0.2,
      "software_development_hours": 0.43,
      "reference_and_learning_hours": 2.53,
      "shopping_hours": 0.03,
      "utilities_hours": 5.0,
      "total_duration_formatted": "14h 27m",
      "very_productive_duration_formatted": "2h 21m",
      "productive_duration_formatted": "7h 12m",
      "neutral_duration_formatted": "57m 32s",
      "distracting_duration_formatted": "1h 44m",
      "very_distracting_duration_formatted": "2h 11m",
      "all_productive_duration_formatted": "9h 33m",
      "all_distracting_duration_formatted": "3h 55m",
      "uncategorized_duration_formatted": "32m 11s",
      "business_duration_formatted": "44m 56s",
      "communication_and_scheduling_duration_formatted": "1h 45m",
      "social_networking_duration_formatted": "1h 15m",
      "design_and_composition_duration_formatted": "14m 53s",
      "entertainment_duration_formatted": "1h 42m",
      "news_duration_formatted": "11m 55s",
      "software_development_duration_formatted": "25m 58s",
      "reference_and_learning_duration_formatted": "2h 32m",
      "shopping_duration_formatted": "2m 1s",
      "utilities_duration_formatted": "5h"
    },
    {
      "id": 1647327600,
      "date": "2022-03-15",
      "productivity_pulse": 82,
      "very_productive_percentage": 47.4,
      "productive_percentage": 39.7,
      "neutral_percentage": 11.1,
      "distracting_percentage": 0.7,
      "very_distracting_percentage": 1.2,
      "all_productive_percentage": 87.1,
      "all_distracting_percentage": 1.9,
      "uncategorized_percentage": 4.4,
      "business_percentage": 21.3,
      "communication_and_scheduling_percentage": 4.8,
      "social_networking_percentage": 1.2,
      "design_and_composition_percentage": 14.8,
      "entertainment_percentage": 0.0,
      "news_percentage": 0.0,
      "software_development_percentage": 11.3,
      "reference_and_learning_percentage": 13.7,
      "shopping_percentage": 0.0,
      "utilities_percentage": 28.6,
      "total_hours": 4.83,
      "very_productive_hours": 2.29,
      "productive_hours": 1.92,
      "neutral_hours": 0.53,
      "distracting_hours": 0.03,
      "very_distracting_hours": 0.06,
      "all_productive_hours": 4.2,
      "all_distracting_hours": 0.09,
      "uncategorized_hours": 0.21,
      "business_hours": 1.03,
      "communication_and_scheduling_hours": 0.23,
      "social_networking_hours": 0.06,
      "design_and_composition_hours": 0.71,
      "entertainment_hours": 0.0,
      "news_hours": 0.0,
      "software_development_hours": 0.54,
      "reference_and_learning_hours": 0.66,
      "shopping_hours": 0.0,
      "utilities_hours": 1.38,
      "total_duration_formatted": "4h 49m",
      "very_productive_duration_formatted": "2h 17m",
      "productive_duration_formatted": "1h 54m",
      "neutral_duration_formatted": "32m 4s",
      "distracting_duration_formatted": "1m 55s",
      "very_distracting_duration_formatted": "3m 27s",
      "all_productive_duration_formatted": "4h 12m",
      "all_distracting_duration_formatted": "5m 22s",
      "uncategorized_duration_formatted": "12m 40s",
      "business_duration_formatted": "1h 1m",
      "communication_and_scheduling_duration_formatted": "13m 46s",
      "social_networking_duration_formatted": "3m 27s",
      "design_and_composition_duration_formatted": "42m 46s",
      "entertainment_duration_formatted": "no time",
      "news_duration_formatted": "no time",
      "software_development_duration_formatted": "32m 36s",
      "reference_and_learning_duration_formatted": "39m 43s",
      "shopping_duration_formatted": "no time",
      "utilities_duration_formatted": "1h 22m"
    }
  ]
export default DataWeek;